### ISSUE TITLE
Force dark mode

### ISSUE THREAD

**Issue by aldbeagle** [ananjaser1211/FloydQ_Reports#100]
I turn this on via developer options, but it seems to then turn off when the phone reboots.
Not a major issue, but an issue nonetheless.
Great rom.

**Comment by ananjaser1211** [comment]
This is not how you turn on dark mode on samsung oneui.

follow the intended method

**Comment by aldbeagle** [comment]
Hi.
Thanks for the swift response.
I am aware that dark mode can be turned on via the display settings, but for some apps, this doesn't work, my Barclays app in this instance.
Using force mode, it does work, but will reset to off (most times) on reboot.
Regards
