### ISSUE TITLE
[BUG] Audio Random muting

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#103]
This is a continuation of #59.

As this bug is still not resolved. 

Previously reported in #33 The phone gets muted and the only way to unmute it is a restart.

Logs from the issue provided by @MTsCetin [Here](https://github.com/ananjaser1211/FloydQ_Reports/issues/59#issuecomment-633202401)

Still not clear what causes this, no clear pattern, the issue has not happened with me on V2 yet but i wont rule it out as "Fixed" till after testing starts.

**Comment by MTsCetin** [comment]
Hi Anan, thank you for this wonderful rom!
I am almost sure that plugging my car's aux cable to my phone's headphone jack causes this issue. (it triggers a random countdown somehow?)
*I have no headphones with headphone jack connection right now, I'll get one and try to reproduce the issue with it.

**Comment by ananjaser1211** [comment]
Good news regarding this bug, with some AudioHAL changes, i havent had the audio mute issue (while having a simcard in the phone + multiple apps pinging notifications all night)

which usually would break, we might have fixed the issue. will update the issue after testing it for more time this week

**Comment by ananjaser1211** [comment]
Alright. i can safely say the issue is no longer there. (i just hope no random person living in the bahamas manages to trigger the mute again lol) 

with sim + all my social apps pinging multiple times a day. audio is still rock solid.
