### ISSUE TITLE
[BUG]random crashes while using phone

### ISSUE THREAD

**Issue by hassaan1234** [ananjaser1211/FloydQ_Reports#108]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
Refer to #7 . if your issue is something else, write a proper report
