### ISSUE TITLE
[BUG] Beauty Mode FC in Front Cam

### ISSUE THREAD

**Issue by RahulHy** [ananjaser1211/FloydQ_Reports#11]
**Describe the bug**
Describe your issue here. 

**To Reproduce**
1. Go to 'Camera App'
2. Click on 'Beauty & Filter option (Front Cam)

**Expected behavior**
Beauty mode should turn on & off. 
**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge

 - Model: SM-G935FD 

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW)

**Comment by ananjaser1211** [comment]
BUG does not seem to happen in the new V2 release. however only the face beauty seems to do any effect

**Comment by royalchowdhury** [comment]
I am facing same issue which is really important like I don't want Smooth face instead I like real face but when the Beauty mode is Off still it applies Softer Skin/Beauty Effects automatically. And FC each time try to make the skin to level 0. 
And Live focus not working! (Server Error/Circle keeps running)
