### ISSUE TITLE
(Request) Navigation Bar

### ISSUE THREAD

**Issue by jonnycena5** [ananjaser1211/FloydQ_Reports#110]
Maybe I am dumb when it's existing but i can't find the option for enabling the Navigation Bar....
When it doesn't exist then can you add It?

Thanks for the hard work!

Greetings from Hungary

**Comment by ananjaser1211** [comment]
it exists already in the ROM, in the AROMA menu.

You first enable it in Aroma. and it will show up once you boot. (if you flashed the BLE.zip fix, it will be disabled it permanently)

then you can enable it / gestures from settings > display

the blezip + nav will be merged in V2

**Comment by jonnycena5** [comment]
What is the aroma menu?

**Comment by jonnycena5** [comment]
How can i find it?

**Comment by ananjaser1211** [comment]
its the installer that lets you choose options when you flash the ZIP.
