### ISSUE TITLE
Sim Change Error 

### ISSUE THREAD

**Issue by tranthuhang98** [ananjaser1211/FloydQ_Reports#111]
After installing, there is a notification from CID Manager that sim change and required restart. I tried to turn off the notification but it cannot be turned off.

The notification will appear and fix on the screen after any restart, and cannot do anything else. 

I tried to restart as following the sim change notification and restart, but it endless restart ( I did it for 10 times, and it still appear on the screen). 

My phone is Samsung S7 edge dual sim.

**Comment by ananjaser1211** [comment]
this might be because it could not find a matching OMC to your country, as a workaround you can remove CIDManager apk from system/system/priv-app in TWRP file manager (mount system in twrp then go to file manage and then that path)

This should not be an issue with V2 as it adds pretty much most of the countries

**Comment by tranthuhang98** [comment]
Thanks for your advice. You might be right with the OMC, I tried both Singapore and Malaysisa as I'm using 2 sims from these two countries, but both are not working. Therefore, I turn back and using light rom now instead. I will wait for version 2 then

**Comment by alok2688** [comment]
hii does this rom work with Indian Sim Card?

**Comment by BBN1987** [comment]
> hii does this rom work with Indian Sim Card?

Yes it work with all Indian SIM cards

**Comment by akramshahid314** [comment]
> After installing, there is a notification from CID Manager that sim change and required restart. I tried to turn off the notification but it cannot be turned off.
> 
> The notification will appear and fix on the screen after any restart, and cannot do anything else.
> 
> I tried to restart as following the sim change notification and restart, but it endless restart ( I did it for 10 times, and it still appear on the screen).
> 
> My phone is Samsung S7 edge dual sim.

This is because of your CSC selection select your country during CSC selection instead of auto or previous.. this issue will resolve 100%
