### ISSUE TITLE
[BUG]Rebooting Phone Resets Quick Panel Layout with ExtraCSC toggles enabled

### ISSUE THREAD

**Issue by rock6663** [ananjaser1211/FloydQ_Reports#113]
When i reboot my phone my quick panel layout resets back to stock layout

**Comment by SkyrilHD** [comment]
Can you try flashing the ROM again without selecting "Extra Toggles"?

**Comment by rock6663** [comment]
> Can you try flashing the ROM again without selecting "Extra Toggles"?

Can i dirty flash ?

**Comment by SkyrilHD** [comment]
it's worth a try but I think it should be okay

**Comment by rock6663** [comment]
After dirty flashing rom without first 3 csc options problem solved @ananjaser1211 you should see this

**Comment by ananjaser1211** [comment]
Ill re-open this as it is still a bug in the ROM, for visibility
