### ISSUE TITLE
[BUG] Dev Options Gpu Watch crash settings

### ISSUE THREAD

**Issue by UntriexTv** [ananjaser1211/FloydQ_Reports#115]
I was watching and trying settings in developer options and when I turn GPU Watch on settings keeps crashing. I can open settings, but not developer settings. Restarting the phone fixes crashing by disabling GPU Watch. But when I enabled it, it happened again.

**Comment by ananjaser1211** [comment]
Samsung Broke GPUWatch in April and higher security patch. they have not fixed it yet.

the feature is broken on the S9 Note 9 and S10 right now
