### ISSUE TITLE
[BUG] Moving apps data to sdcard via settings or storage booster

### ISSUE THREAD

**Issue by DivineForce** [ananjaser1211/FloydQ_Reports#12]
all info are attached in the ZIP.
the issue is faced once you navigate to:
settings -> apps ->[any app that is movable to sdcard] -> storage -> change -> SD card -> move
then it fails saying storage is full same error could be found in yuva app that moves apps by default to sdcard

![photo_2020-04-21_11-55-46](https://user-images.githubusercontent.com/37049174/79846390-10189b00-83c7-11ea-95f1-bae32016a3ab.jpg)
![photo_2020-04-21_11-55-50](https://user-images.githubusercontent.com/37049174/79846396-11e25e80-83c7-11ea-87e9-312efff22b37.jpg)

[Moving Apps Logket.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4508813/Moving.Apps.Logket.zip)

**Comment by akramshahid314** [comment]
While flashing zip invalid zip format error

**Comment by ananjaser1211** [comment]
This bug seem to have made it's way back into the public v2 build. Bummer

**Comment by ananjaser1211** [comment]
Ok i found the cause of this issue, related to knox mdma / sdk perms

if you want to move apps to sdcard you have to enable KNOX Apps in aroma
