### ISSUE TITLE
[BUG] camera keep stopping 

### ISSUE THREAD

**Issue by akramshahid314** [ananjaser1211/FloydQ_Reports#120]
Randomly working camera app.. often closes itself 
![Screenshot_20200623-215303_One UI Home](https://user-images.githubusercontent.com/66011898/85432533-876fd400-b59c-11ea-9a19-aa26abad6c27.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by SkyrilHD** [comment]
Can you attach logs?

**Comment by shariq342** [comment]
Clear Data and Cache of Samsung Camera

**Comment by ananjaser1211** [comment]
Thanks for the logs /s
