### ISSUE TITLE
Battery draing too fast and stop charging at 94 % even charger is connected and status shows charging 

### ISSUE THREAD

**Issue by akramshahid314** [ananjaser1211/FloydQ_Reports#122]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
Stop opening issues with little to ZERO information. report bugs properly.
