### ISSUE TITLE
[BUG]Camera on video mode

### ISSUE THREAD

**Issue by albertodurmiendo** [ananjaser1211/FloydQ_Reports#124]
**Describe the bug**
I don't know what's happen but suddenly my camera crash at video mode.

**To Reproduce**
Open Camera and select video mode

**Screenshots**
![Screenshot_20200624-130950_Device_care 1](https://user-images.githubusercontent.com/49085370/85566727-e13ad180-b662-11ea-9353-675ba96276c3.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930FD
 - V2.0

**Additional context**
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4825680/log_e.log)

**Comment by ananjaser1211** [comment]
`06-24 21:33:11.039 17896 17896 E AndroidRuntime: FATAL EXCEPTION: main
06-24 21:33:11.039 17896 17896 E AndroidRuntime: Process: com.sec.android.app.camera, PID: 17896
06-24 21:33:11.039 17896 17896 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
06-24 21:33:11.039 17896 17896 E AndroidRuntime: 	at com.sec.android.app.camera.util.DimensionWrapper.getPreviewTop(Unknown Source:20)`

Was the camera APK changed ? dirty flashed ? any external MODs , fonts , UI changes etc.

finally did you try to wipe camera data. this crash is a change in the APK

**Comment by albertodurmiendo** [comment]
I'm from clean install, the camera is working from that and haven't tried again after, no external mods, my font is SamsungOne

**Comment by albertodurmiendo** [comment]
Closing it, the cause is my Screen Resizer app, Sorry

**Comment by ananjaser1211** [comment]
Glad it was resolved.

**Comment by albertodurmiendo** [comment]
Thanks for the info and a great rom.

**Comment by albertodurmiendo** [comment]
By the way, @ananjaser1211 I got another one, bixby setup in assistive menu is just showing logo and then disappear? what do you think the problem? my screen resizer is uninstalled by the way.

**Comment by ananjaser1211** [comment]
> By the way, @ananjaser1211 I got another one, bixby setup in assistive menu is just showing logo and then disappear? what do you think the problem? my screen resizer is uninstalled by the way.

besides making sure you installed bixby with the ROM, id try to uninstall existing updates. then re-updating bixby from galaxy store, clearing its data. and try to lunch bixby from the "bixby has been updated" notification instead of assistant menu.

there are 2 buttons i remember, hold and press. they dont work that well
