### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by limvaldez** [ananjaser1211/FloydQ_Reports#125]
**Bluetooth miscs in developers option**
When you set a setting for Bluetooth, the setting you had been set will not been save when you minimize, close or back the developers option module. I connected my Bluetooth earphones, but still didn't save the settings i had been set.

![USER_SCOPED_TEMP_DATA_orca-image--215798563](https://user-images.githubusercontent.com/64057182/85650825-ea668580-b6d8-11ea-9f7b-821055eeeb7f.jpeg)

**Comment by chrismin13** [comment]
That is expected behavior. You must first be connected to a Bluetooth device capable of the profile and settings you select. Otherwise, it'll go back to the default. 

Not a bug of this ROM.

**Comment by ananjaser1211** [comment]
I dont debug developer mode options. those are universal and would fail/work the same way as an official Q device
