### ISSUE TITLE
[BUG] Unstable connection - Wifi and mobile data

### ISSUE THREAD

**Issue by SpikeJr** [ananjaser1211/FloydQ_Reports#126]
After a certain time the wifi and the mobile data no longer works. I still can receive phone calls, but the internet go so slow. I've tried with Auto CSC, ZTO and another one that now I can't remember (Saudi Arabia), but the issue still happens
I have to restart the phone to solve the problem
I haven't gather any logs because I don't know when it happens
Until now this happens once per day
Device: SM-G965F

**Comment by SpikeJr** [comment]
So, I've tried changing the MAC option. The wifi works for a few moments (sometimes not even minutes) before becomes unstable again.
I'm actually using data mobile to write this. Until now all good

**Comment by ananjaser1211** [comment]
move discussion to #119
