### ISSUE TITLE
[BUG]? no camera resolution setting

### ISSUE THREAD

**Issue by Titbit-21** [ananjaser1211/FloydQ_Reports#127]
I can not choose the size of the photo. G935FD
![Screenshot_20200625-172026_Camera](https://user-images.githubusercontent.com/67420615/85719669-126ddd00-b709-11ea-9615-eac53f0bc717.jpg)

**Comment by ananjaser1211** [comment]
This will add camera resolution changing again. and will enable AR Emoji

[CamFeature.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4840528/CamFeature.zip)

**Comment by arkgnan** [comment]
![Screenshot_20200628-154847_Galaxy Store](https://user-images.githubusercontent.com/17277219/85942983-39b9e980-b957-11ea-9b33-53b3861fb823.jpg)
AREmoji still won't work

**Comment by ananjaser1211** [comment]
> ![Screenshot_20200628-154847_Galaxy Store](https://user-images.githubusercontent.com/17277219/85942983-39b9e980-b957-11ea-9b33-53b3861fb823.jpg)
> AREmoji still won't work

This is not ARemoji , this is my emoji maker, and is not included in the ROM because the app is over 150MB in size.
AR emoji is the 3D Face stickers you put on your face.

**Comment by arkgnan** [comment]
Ah I see... sorry I didn't know it, I think it is one package with ARemoji

**Comment by ananjaser1211** [comment]
No problem. did the picture resolution changer work ?

**Comment by Titbit-21** [comment]
Yes. Resolution is work. Thank you bro.  I don't use emojy14:04, 28 июня 2020 г., AnanJaser <notifications@github.com>:
No problem. did the picture resolution changer work ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by usmangulzar020** [comment]
which version of ar emoji is compatable i tried different version but still doesnot work in one ui 2.0 s7 edge?

**Comment by Kazi8869** [comment]
Pro mod not work. After set exposure higher than 1sec camera freezing after shot.
