### ISSUE TITLE
[BUG] the othert part heard low ând tubby sound on phone calls. 

### ISSUE THREAD

**Issue by nicohak** [ananjaser1211/FloydQ_Reports#130]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
More information please. Logs of outgoing calls. a recording if possible. 

What CSC being used, what S7 variant. what carrier aswell if possible

VoLTE based or 3G call

**Comment by nicohak** [comment]
G935F model
ROM CSC ,DIGI MOBIL Provider
Volte voice call.
About registered coversation ,I don't have any.
I hear very well the other part, but they don't hear me very well.
Low and tubby voice.
Maybe a microphone issue.
Thanks a million!


More information please. Logs of outgoing calls. a recording if possible.
What CSC being used, what S7 variant. what carrier aswell if possible
VoLTE based or 3G call

**Comment by ananjaser1211** [comment]
and your microphone i assume is working fine ? (can you test in the voice recorder app, because calls and normal recording run on different methods)

**Comment by nicohak** [comment]
Having Q rom, my wife told me that
she's hearing me bad during phone calls.
In fact I verified changing the phones, so I asked her to call me from my 
phone to hers and yes  ,the sound was low.
I restored a Pie rom back on my phone and calling her she said that has the 
sensation to he close to me.
That's why I think that maybe it's a mic issue because of the new Q software.
I'm almost ashamed to tell this.
I'm not arguing, that has to be clear.
I imagine what a hell to work you made for us.
I'm only trying to reveal some problems and I'm very sorry because I don't 
have the skills to help  you more.
Thank you very much indeed  !



and your microphone i assume is working fine ? (can you test in the voice 
recorder app, because calls and normal recording run on different methods)

**Comment by ananjaser1211** [comment]
Dont worry, this page is for reporting issues. so im trying to get all the information i can to try and figure out what is broken

Here are 2 things to try

1) Flash this ZIP file and see if the issue changes or is gone

[Audio.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4847314/Audio.zip)

2) if it did not work, reflash the ROM and in CSC select XSG or DBT instead of auto or previous

let me know if any of these fix your issue or not

**Comment by nicohak** [comment]
Clean Flashed again the Rom , choose my csc , sound zip and new Cronos kernel.
Faced a wired issue, "no available network "
Dirty reflash the Rom, this time choosing OMC, flash the new Cronos kernel 
and all issues gone.
Very good sound now , no overheating phone, 100 % charged.
The only change I made, was phone Mac instead randomized.
Thank you very much for all  !


Dont worry, this page is for reporting issues. so im trying to get all the 
information i can to try and figure out what is broken
Here are 2 things to try
Flash this ZIP file and see if the issue changes or is gone
Audio.zip
if it did not work, reflash the ROM and in CSC select XSG or DBT instead of 
auto or previous
let me know if any of these fix your issue or not

**Comment by arkgnan** [comment]
after flash Audio.zip my phone can't play any audio/video sound, like youtube, music and another app.
I try to log the error and found error audiohalservice and listAudioPatches error -32

@ananjaser1211 could you checked it?
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4888436/log_e.log)

**Comment by ananjaser1211** [comment]
> after flash Audio.zip my phone can't play any audio/video sound, like youtube, music and another app.
> I try to log the error and found error audiohalservice and listAudioPatches error -32
> 
> @ananjaser1211 could you checked it?
> [log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4888436/log_e.log)

i just saw this my bad. i forgot to include a lib file in this temp patch, it will be included in V3
