### ISSUE TITLE
Volume Up on Headphones

### ISSUE THREAD

**Issue by Chbartek99** [ananjaser1211/FloydQ_Reports#132]
Can't I give more volume on headphones than 90 (60%), max 150 (100%)? As I slide my finger over 60% comes back. 😡 I tried to reset the settings to the factory values ​​but it did nothing. 😔 Other applications also cannot be increased.
![20200630_013001](https://user-images.githubusercontent.com/46648761/86066014-4af71900-ba71-11ea-8819-4892ff45e179.jpg)
![20200630_013016](https://user-images.githubusercontent.com/46648761/86066029-52b6bd80-ba71-11ea-81b6-2c9304d3a45f.jpg)

**Comment by Chbartek99** [comment]
@ananjaser1211 what else should I send to see the problem

**Comment by Chbartek99** [comment]
@ananjaser1211 what else should I send to see the problem

**Comment by ananjaser1211** [comment]
This seems like an issue with sound assistant goodlock module. tried without it ? i dont have it installed right now and volume works just fine

**Comment by Chbartek99** [comment]
Thank you very much.  I am reporting an error in the sound assistant theme.  Through it I can not turn up the volume because the alert does not pop up.  Please fix it 😁
