### ISSUE TITLE
Infinity Samsung Animation Boot Loop

### ISSUE THREAD

**Issue by Afanalbeto** [ananjaser1211/FloydQ_Reports#133]
Please, man i have a problem, i have tried to install new version of Floyd Q rom v2.0, but i dont know what is causing the boot loop on animation, i have tried all the possibilitie but i dont get sucess, i have wiped all partition and have cleaned data on twrp-wipe-formatdata but dont fix the problem, please man i so much want to install this new version but i have get this problem :/

I have tried install v2.0 and I are using the Floyd Q rom v1.0 always, I install the version 1.0 and dont get any error or problem why?

My Twrp: 3.3-1-Moro

Sorry for my bad English
Im from Brazil... Thanks for your porpose

**Comment by ananjaser1211** [comment]
Verify MD5 hash as guided in the installation thread and report the results there, this page is for reporting issues.
not install issues

check MD5, redownload the ROM , reflash latest stock etc
