### ISSUE TITLE
[BUG]Battery Draining fast

### ISSUE THREAD

**Issue by akramshahid314** [ananjaser1211/FloydQ_Reports#134]
As you mentioned after flashing the new kernel 4.5 battery discharge rate is increased. According to your advised I installed advance charging module with magisk but with this module battery only charged upto 75% after this no charge sign appear.. now I have Uninstalled that module battery charged 100% after using some time I noticed many times that battery health is not good with this rom.. now I have connected charger data connection on and wifi Hotspot on. Instead of charging battery is going down from 28 to 14 % now.. I am not a keen developer so I hope show will understand the problem I am facing

**Comment by UntriexTv** [comment]
I have this problem too. But I didn't install any module I just flashed kernel 4.5 and my phone refused to charge sometimes. I was thinking that was power bank issue (i was on a trip for 4 days) so I solved it by turning it off (then it charged to 100%). But at home, I got stuck with a fast charger (original by Samsung) on 70%. I replugged the charger to the phone. It starts charging but it stops after a while (still not more than 70%).
I saw that lot of people had same problem in xda thread and didn't find any explanation or fix (aside from turning off mobile or flashing kernel 4.0).

**Comment by ananjaser1211** [comment]
Monitor your background usage to report actual usable data, "draining fast" tells me nothing.
most likely it is some background app or social app that is using alot of energy. 

oneui 2 is heavier and will consume more power under similar usages. it is just how it is with Q.

regarding the 70% Bug, open a new issue for it and submit logs. i dont have this issue with 4.0 and 4.5 kernels on my S7E
