### ISSUE TITLE
No audio going through in volte plus calls

### ISSUE THREAD

**Issue by rock6663** [ananjaser1211/FloydQ_Reports#135]
I can hear them but they cant hear me in volte plus calls 
screenshots:
![20200705_031654](https://user-images.githubusercontent.com/48176390/86539275-c9393c80-bf03-11ea-8839-246a788aee9d.jpg)

**Comment by ananjaser1211** [comment]
I cant help with this. as i dont have VoLTE in my sim, nor do i have volte+

i know for a fact that normal VoLTE works just fine. so use that instead. and be sure you use your own country OMC

**Comment by rock6663** [comment]
@ananjaser1211 it cant be turned off if you talking someone who has phone that supports volte plus it appears it has only one way to bypass closing volte which i cant right now cause selecting volte toggle in aroma bugs quick bar also no volte on more connection settings right now
