### ISSUE TITLE
Phone overheated during use

### ISSUE THREAD

**Issue by Zlatan117** [ananjaser1211/FloydQ_Reports#137]
**Describe the bug**
phone overheated during normal use. 

**Smartphone
 - Device: [ Galaxy S7 edge]

**Comment by DirNotAvailable** [comment]
Had the same issue, I guess it is with some phones in S7 series especially International FD Models. Try to go for minimal and avoid unnecessary BLOAT. Further you can use custom clock frequencies and voltage values, it greatly reduce heating and other lagging, hanging issues.

- Here is a fantastic profile for kernel tuning:
       [https://forum.xda-developers.com/s7-edge/development/kernel-profile-lagterminator-v1-t3956155](url)
- Morever you can also fine tune the KERNEL according to your liking, here is a guide for that:
       [https://androidmodguide.blogspot.com/](url)

**Comment by irfankhokhar** [comment]
I have also same issue. Battery overheated when I use my phone. 
Model: S7 Edge fd

**Comment by ananjaser1211** [comment]
Monitor your usage. heat does not come out of nowhere. and use 4.5 kernel.

One ui 2 is significantly more heavy than Pie. the same usage will use more power in some areas.

make your own configs, do not use others. you dont know what they change.
