### ISSUE TITLE
Fingerprint sensor registeration not working

### ISSUE THREAD

**Issue by khant2014** [ananjaser1211/FloydQ_Reports#138]
every time i want to register my finger print, it says "Sensor is dirty" and quit to "Biometric reference"menu automatically eventhough my FP sensor is not dirty.

Version : 2
Phone : S7edge G935FD

**Comment by ananjaser1211** [comment]
Q sensor HAL is more sensitive, and any slight scratches on your sensor , finger , blemishes or such will cause issues with calibration.

i wont be doing anything about this as it works just fine except for 3 people so far.

one of them had a fully broken FP sensor all together.

**Comment by khant2014** [comment]
thank u for your reply
