### ISSUE TITLE
[BUG] Camera Buffer crash (Camera stops working until a reboot)

### ISSUE THREAD

**Issue by MightyCrusier** [ananjaser1211/FloydQ_Reports#140]
**Describe the bug**
The camera app crashes every so often, I am aware that this bug was mentioned in #120, but this seemed to be a one time only bug. On my end the camera app will start to crash at random times and requires a reboot to function properly again, clearing cache and data of the camera app do it no avail either. Note that once the app starts to crash it won't open until reboot. (This applies to every app that requires camera to start)

**To Reproduce**
1. Launch the camera app
2. App crashes

**Expected behavior**
I think it's self-explanatory.

**Screenshots**

![Screenshot_20200710-112046_One UI Home](https://user-images.githubusercontent.com/39172116/87139621-96df6480-c2a0-11ea-814f-ebe30a4f124a.jpg)

**Smartphone:**
 - Device: Galaxy S7 Edge
 - Model: G935F

**Additional context**
LOGS:
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4902272/log_e.log)

**Comment by ananjaser1211** [comment]
Can you go to camera settings and disable shot suggestions / document scan features.

those two seem to be causing camera to crash for my testers. let me know if it fixes your crash

alternatively you can wipe camera data and just tick them off if they are on

**Comment by MightyCrusier** [comment]
> Can you go to camera settings and disable shot suggestions / document scan features.
Can't find those settings in the app, could you pin-point exatly where they are, maybe in a screenshot by any chance?

**Comment by ananjaser1211** [comment]
> > Can you go to camera settings and disable shot suggestions / document scan features.
> 
> Can't find those settings in the app, could you pin-point exactly where they are, maybe in a screenshot by any chance?

[camfeat.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4941033/camfeat.zip)

It is disabled in my app so i cant send the exact location, Flash this zip which will disable those broken features. after that wipe data for samsung camera app from settings > apps > show system apps

if the camera continues to crash, take another log_e. let me know how it goes

**Comment by MightyCrusier** [comment]
Ok, flashed and wiped camera data. Will update, if I get a crash again.

**Comment by MightyCrusier** [comment]
Unfortunately, after running fine for a whole day, it crashed again today.
Here's log:
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4943800/log_e.log)

**Comment by ananjaser1211** [comment]
> Unfortunately, after running fine for a whole day, it crashed again today.
> Here's log:
> [log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4943800/log_e.log)

Seems like a buffer issue hm, what usually do you use in camera (do you take more photos, or more videos basically)

**Comment by MightyCrusier** [comment]
>(do you take more photos, or more videos basically)

Definately more videos.

Here's a video so you can better understand what's happening on screen:
https://youtu.be/qVbzHkLq3yM

**Comment by ananjaser1211** [comment]
> > (do you take more photos, or more videos basically)
> 
> Definately more videos.
> 
> Here's a video so you can better understand what's happening on screen:
> https://youtu.be/qVbzHkLq3yM

Alright this makes a bit more sense now, buffer allocation fails and it stops generating more buffers

07-19 16:00:25.209  3609 12955 E Camera3-Stream: returnBuffer: Stream 0: timestamp 15000000 is not increasing. Prev timestamp 15000000
07-19 16:00:25.209  3609 12955 E Camera3-OutputStream: returnBufferCheckedLocked: A frame is dropped for stream 0 due to buffer error.

I honestly do not know if i can fix this, ill try to do some tests next week (as V3 is dropping tmw, it will have this bug)

Can you tell me your video settings, quality , and avg length before it just stops working.

Thanks

**Comment by MightyCrusier** [comment]
>Can you tell me your video settings, quality , and avg length before it just stops working.

Usually I record 4K at 60fps, it never crashes during the recording, but rather seems to randomly start doing what's shown in the video after a day or two. Once it starts doing that, there's no other fix than just restarting the device

**Comment by Cvolton** [comment]
I believe this is related to the bug where sometimes when you quickly close and enable the camera, the camera server dies for a split second and the phone thinks it has 0 cameras during this time. This is hinted at by this log line:
`07-19 15:53:55.210 12706 12758 E AndroidRuntime: java.lang.IllegalStateException: There is no capability for : 0`
Except here it seems that the phone never recovers from this state, whereas the device recovers very quickly (fast enough for the bug not to persist after a restart of the camera app) during the times I've observed this. I've also never observed this with the stock camera app.

What was the last camera-related thing you were doing before it happened again? The only scenario I can think of where this could happen with the stock camera app is recording a video, stopping, switching to photo right after and then closing the app right before the mode loads.

**Comment by MightyCrusier** [comment]
>What was the last camera-related thing you were doing before it happened again?

Yesterday I took a couple of photos. Today I haven't touched the camera app, and when I did, the crash occurred.
Than, I took the log, restarted the device and started to stress-test it, where I basically reopened the app, until it crashed. Took a couple of tries and the app died again.

>The only scenario I can think of where this could happen with the stock camera app is recording a video, stopping, switching to photo right after and then closing the app right before the mode loads.

Tried doing what you described there, and did not encounter the crash.

**Comment by sahilmubarak** [comment]
I've got the same problem

**Comment by ananjaser1211** [comment]
A little update about this bug. it is not logged as it happens much earlier, but this is an FDSAN error

```
signal 35 (<debuggerd signal>), code -1 (SI_QUEUE), fault addr --------
Abort message: 'attempted to close file descriptor 146, expected to be unowned, actually owned by unique_fd 0xe9805074'
```

FDSan (File descriptor sanitizer) is a new addition to android Q . our camera is closing FDs it does not own which faults fdsan and terminates it, it performs few warnings until it decides to fully disable the libexynoscamera all together.

Right now this issue happens on Floyd Q and AOSP Q using Pie camera blobs. 

ivan_meler (Main AOSP dev on S7) mentioned to me that this issue does not occur under oreo blobs on AOSP. so i will be trying to make the stock S7 Edge libs work somehow, i very much doubt it will work however as we barley had any luck under pie.

will see how it goes, or we find a hack to disable FDSan on Q

**Comment by qstar-inc** [comment]
Hi, just wanted to drop by and report that the crash still happens on v4. (Full system wiped, camera data wiped). Although its not really a big issue for me personally as I barely use camera, but still happy to inform.

**Comment by SypeR54** [comment]
@qstar-inc Can you try to get new logs? Because its working on all V4 users.
