### ISSUE TITLE
[BUG]Screen doesnt turn off automatically

### ISSUE THREAD

**Issue by aemtox** [ananjaser1211/FloydQ_Reports#141]
**Describe the bug**
The problem i am facing is present since the installation of FloydQ 2.0 on my S7 Edge. I've activated the system included feature to turn off the screen after a defined time but it doesnt work. I had it set to 30 secs, afte that ive tried it with 15 and right now its set to 60 with the bug remaining. 

**To Reproduce**
1. Turn on screen
2. Wait for nothing to happen

**Expected behavior**
The phone turns of the screen in an automatic behavior.

**Screenshots**
Won't help in that special case

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model: G935F

**Additional context**
[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4908776/log_All.log)

I am not really into writing code or reading out bugs for android systems, but I already saw something from the UiThreadMonitor that could be it. It called a SetAwake function, but maybe you know more.

**Comment by aemtox** [comment]
[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4908776/log_All.log)

**Comment by ananjaser1211** [comment]
This is caused by some 3rd party app that keeps your phone awake. i cant help with that. probably some app that shows an overlay, some media player. who knows

You have an app called tapatalkpro that might be it, im not sure

i have tested 15sec / 30 sec timeout on V2 now. works as expected.

**Comment by aemtox** [comment]
Ok but the same apps had been present on the stock firmware i had installed before flashing to FloydQ. This seems to be a problem related to this firmware, if its by the side of Android 10 or other things is what I cant tell.

Thanks for taking care about of problem and releasing this ROM by the way. :)

**Comment by ananjaser1211** [comment]
> Ok but the same apps had been present on the stock firmware i had installed before flashing to FloydQ. This seems to be a problem related to this firmware, if its by the side of Android 10 or other things is what I cant tell.
> 
> Thanks for taking care of problem and releasing this ROM by the way. :)

I would still say it is some APP issue, app behaviour changes from Android ver to another. i am sure if it was a ROM issue we would have seen it by now. as i keep 30 sec time out always. 

double check apps with overlay permission (ones that can write on screen such as facebook messenger etc. as those usually keep the screen on)

goodluck and thanks for the kind words
