### ISSUE TITLE
[BUG] Phone get overheat and the battery has run out

### ISSUE THREAD

**Issue by Zlatan117** [ananjaser1211/FloydQ_Reports#143]
**Describe the bug**
During the night the phone gets overheat (I wasn't using that) and the battery has run out.

**Smartphone (please complete the following information):**
 - Galaxy S7 edge
 - SM-G935F

**Comment by JP-BD** [comment]
Not sure yet if something´s wrong at my end, but my device will overheat noticeably for no apparent reason and then do a soft reset two to three times per day. Still trying to recreate. Using SM-G930F, Rom v2, Kernel v4.5, Magisk v20.4, full wipe/format before flash, no nand/titan backup restore during setup whatsoever. Maybe related to the above post. Battery seems to discharge faster while device overheats. If somebody tells me how two provide logs for this, I´ll try.

**Comment by ananjaser1211** [comment]
When the crash happens (i.e when your phone reboots) using root explorer or such copy the file /proc/last_kmsg or follow the main post to pull the kernel log using your PC

this report is very bizarre and has zero information i can work with.

**Comment by JP-BD** [comment]
Strangely, the restart didn´t happen again since I wrote. As soon as it does though I´ll attach the log and if it doesn´t I at least learned how to pull logs from an emulator... Thanks in advance.
