### ISSUE TITLE
Lockscreen lags and predictive setting not working in samsung keyboard

### ISSUE THREAD

**Issue by frontdev10** [ananjaser1211/FloydQ_Reports#144]
**Lockscreen lags and predictive settings not working **
The lockscreen lags whenever i swipe to enter the pattern, pin or other. the samsung keyboard predictive settings doesnt predict whenever i type anything and it doesnt show any suggestion or any words predicting whatever i type

**Comment by ananjaser1211** [comment]
LAG is expected to happen when you run an OS twice as heavy as stock i wont be doing anything special about it as thats how it is. predictive text works just fine here, make sure you installed languages . there is a small circle you press to swap between predictive text and options

**Comment by frontdev10** [comment]
Thats true, but as soon as u swipe to the pattern lock I can see the icons appeared ( call and camera) and then vanished
