### ISSUE TITLE
[BUG] Samsung dialer crashes when viewing call history

### ISSUE THREAD

**Issue by Ubsefor** [ananjaser1211/FloydQ_Reports#145]
**Describe the bug**

Samsung Dialer crashes when viewing call history

**To Reproduce**

Open the dialer and view call history of specified contact

**Expected behavior**

No crashing while viewing call history

**Smartphone (please complete the following information):**

 – Device: SM-G965F

**Logs**

[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4931592/log_All.log)

**Additional information:**

Dirty flashed over V2.0; added system sounds to /system/media/audio; magisk rooted; all bloatware and all features ticked in aroma installer exept for bixby vision; flashed wifi_blobs.zip and CamFeature.zip and reflashed CronosKernel 4.0

**Comment by ananjaser1211** [comment]
This is related to samsung firewall app (what they name "call blocking") which stopped working in V2 for some reason.

**Comment by ananjaser1211** [comment]
The bug has been fixed, it was due to an old CSC line that enabled custom callblocking app from samsung that does not work properly on Q

i have reverted to stock callblocking behaviour, which should fix the dailer FC aswell

**Comment by Ubsefor** [comment]
Thank you for your hard work!
