### ISSUE TITLE
[BUG] No Allowed Devices Option in Mobile Hotspot

### ISSUE THREAD

**Issue by EchoEcho24** [ananjaser1211/FloydQ_Reports#146]
There's no "Allowed Devices" option in Mobile Hotspot settings.

**Comment by ananjaser1211** [comment]
> There's no "Allowed Devices" option in Mobile Hotspot settings.

Allowed devices option was removed in OneUI 2.0. not there on my S9.

**Comment by EchoEcho24** [comment]
Ow, okay. Thanks so much for giving effort to this rom. 👌👌
