### ISSUE TITLE
[BUG] Bixby settings won't open.

### ISSUE THREAD

**Issue by oopsitsdeleted** [ananjaser1211/FloydQ_Reports#147]
**Describe the bug**
When i try to open bixby settings either by going into bixby's app info in settings and pressing the gear icon or asking bixby to open bixby settings, my phone just hangs for a while and then just goes back to the previous screen i was on.

**To Reproduce**
1. Go to 'settings, apps, bixby'
2. Click on 'the gear icon'
3. See error

**Expected behavior**
The phone hangs for a few seconds and then brings you back to the apps list in settings.

**Screenshots**
i have no screenshots.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7 Edge]
 - Model: [e.g. G930FD]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
Refer to the notes

- You cant use Bixby in settings > Advanced feature due to no H/W Button

This is how Q bixby behaves.
