### ISSUE TITLE
[BUG] iluminacion edge

### ISSUE THREAD

**Issue by NELSON777A** [ananjaser1211/FloydQ_Reports#150]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
Report properly

**Comment by NELSON777A** [comment]
La notificacion no tiene movimiento

**Comment by ananjaser1211** [comment]
i dont speak spanish, google translate is not giving good result. i think you did not install edge light in aroma , or did not select " ALL APP" and "APP COLOR" in edge light setting
