### ISSUE TITLE
[BUG] Camera issues

### ISSUE THREAD

**Issue by aykuxt** [ananjaser1211/FloydQ_Reports#152]
**Describe the bug**
The camera is very unstable. It takes very long to start and it also effects some other apps like Telegram and WhatsApp.

**To Reproduce**
1. Go to Telegram
2. Click on attachment menu
3. The phone freezes some times because of the small camera preview
4. After removing access to camera, no more freezes and everything works

**Smartphone (please complete the following information):**
 - Device:  Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
This is related to #140 buffer issues, i will keep all camera discussion there. you can add the comment.
