### ISSUE TITLE
[BUG] Magisk wont install, magisk bootloop

### ISSUE THREAD

**Issue by limvaldez** [ananjaser1211/FloydQ_Reports#153]
**Describe the bug**
I flash the magisk file. In the first try, magisk did not show in app drawer(it means magisk did not install). The 2nd one, when your phone restarts after magisk installation, your phone will stock in boot logo.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930FD]

PS: I suggest next time to put a magisk in an aroma.

**Comment by ananjaser1211** [comment]
I don't have this issue. Did you change the kernel ?

**Comment by limvaldez** [comment]
> I don't have this issue. Did you change the kernel ?

Not. I just install the whole aroma.

**Comment by limvaldez** [comment]
> I don't have this issue. Did you change the kernel ?

Update: Flash the no-verity v6.1 also flash the magisk v20.4 for successful rooting.

PS: I already installed the magisk

**Comment by ananjaser1211** [comment]
You should have mentioned you flashed magisk v19. Which is old and does not support Q properly last I checked.

You just need to flash magisk v20.4 only. No other zips are needed.
