### ISSUE TITLE
[Bug]Lag in Phone App and Message App in One UI 2.0

### ISSUE THREAD

**Issue by frontdev10** [ananjaser1211/FloydQ_Reports#155]
Lag in Phone and Message App

The ROM is smooth, no problem with any apps except the system app i.e the phone app and the message app.
Whenever i open one of the two apps , it takes 3-4 seconds to load the contents such as the contacts. I hope u improved it in 2.1?

Screenshots
![VideoCapture_20200723-130744](https://user-images.githubusercontent.com/68374623/88262480-ec2a6580-cce5-11ea-8d8c-10ecf4a6b303.jpg)
![VideoCapture_20200723-130830](https://user-images.githubusercontent.com/68374623/88262525-fc424500-cce5-11ea-818d-457829dd103a.jpg)

 
Smartphone
 - Device:  Galaxy S7 edge
 - Model: [e.g. G935FD]

**Comment by ananjaser1211** [comment]
Don't have this issue on my end or reported by testers.

Did you restore system app data for those two apps ? Because this is similar to an issue that happens when the phone isn't wiped

**Comment by frontdev10** [comment]
Pardon me, im kinda noob in this, are u saying I should do a cache wipe??

**Comment by ananjaser1211** [comment]
> Pardon me, im kinda noob in this, are u saying I should do a cache wipe??

When installing this rom you need to wipe data , cache, dalvik and system. and not restore system app data from previous rom

**Comment by irfankhokhar** [comment]
When I install this rom wipe data and external storage but also same problem with messeges app

**Comment by frontdev10** [comment]
> > Pardon me, im kinda noob in this, are u saying I should do a cache wipe??
> 
> When installing this rom you need to wipe data , cache, dalvik and system. and not restore system app data from previous rom

i did those, but i get the same issue, even with one ui 2.1

**Comment by SypeR54** [comment]
@frontdev10 and @irfankhokhar When Phone and Messaging apps dont load anything, can you log it via "LoggingKit -> log_all.bat" ? because looks like apps working but cant loading database. I had that error when i was porting OneUI apps to the Nougat rom. Because of old Contacts database files, it cant load.

Also its working on me without issues. On first installation dont skip and setup your both Google and Samsung accounts.

**Comment by ananjaser1211** [comment]
Can't recreate the issue.  The testers can't either. And there we never logs reported. Closed for now.
