### ISSUE TITLE
[BUG] F2FS and EXT4 on external SD doesn’t work

### ISSUE THREAD

**Issue by Ubsefor** [ananjaser1211/FloydQ_Reports#156]
**Describe the bug**
External SD cards, formatted to f2fs or ext4 are not readable by phone

**To Reproduce**
1. Format external sd using moro twrp to f2fs or ext4
2. Boot into system
3. You will get popup about damaged SD card, suggesting to format it (it formats sd card to FAT32)

**Expected behavior**
A proper F2FS and EXT4 on SD Card support

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model: G935FD

**Additional context**

[log_all.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4968016/log_all.log) – logcat at inserting SD card to booted phone

[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4968018/log_kmsg.log)

![Screenshot_20200723-210949_One UI Home](https://user-images.githubusercontent.com/38097265/88322804-ec4c5480-cd29-11ea-8ee8-3ed12cbc9abe.jpg)

**Comment by ananjaser1211** [comment]
How exactly is that not expected behavior? External SD on oneui is either fat32 or exFAT. It does not read and mount ext4 natively let alone F2FS
You have to use 3rd party apps and you usually create a ext4 partition then create a mount script for it (refer to app2sd softwares on playstore that does this)

Reference : I formatted a 32GB external SD under gparted with ext4 and my stock S9+ could not mount it.

**Comment by Ubsefor** [comment]
> How exactly is that not expected behavior? External SD on oneui is either fat32 or exFAT. It does not read and mount ext4 natively let alone F2FS
> You have to use 3rd party apps and you usually create a ext4 partition then create a mount script for it (refer to app2sd softwares on playstore that does this)
> 
> Reference : I formatted a 32GB external SD under gparted with ext4 and my stock S9+ could not mount it.

OK, Thank you for clearing that out, I strongly believed external SD filesystems such as F2FS and EXT4 are supported

**Comment by ananjaser1211** [comment]
> > How exactly is that not expected behavior? External SD on oneui is either fat32 or exFAT. It does not read and mount ext4 natively let alone F2FS
> 
> > You have to use 3rd party apps and you usually create a ext4 partition then create a mount script for it (refer to app2sd softwares on playstore that does this)
> 
> > 
> 
> > Reference : I formatted a 32GB external SD under gparted with ext4 and my stock S9+ could not mount it.
> 
> 
> 
> OK, Thank you for clearing that out, I strongly believed external SD filesystems such as F2FS and EXT4 are supported

Supported sure. But not implemented. Otherwise it would have just loaded the SD on the s9 (assuming it might have been an s7 bug)

If you want to use F2fs a custom mounting script would be needed. Not sure about F2fs I didn't try those externally

**Comment by Ubsefor** [comment]
> > > How exactly is that not expected behavior? External SD on oneui is either fat32 or exFAT. It does not read and mount ext4 natively let alone F2FS
> > 
> > 
> > > You have to use 3rd party apps and you usually create a ext4 partition then create a mount script for it (refer to app2sd softwares on playstore that does this)
> > 
> > 
> > > 
> > 
> > 
> > > Reference : I formatted a 32GB external SD under gparted with ext4 and my stock S9+ could not mount it.
> > 
> > 
> > OK, Thank you for clearing that out, I strongly believed external SD filesystems such as F2FS and EXT4 are supported
> 
> Supported sure. But not implemented. Otherwise it would have just loaded the SD on the s9 (assuming it might have been an s7 bug)
> 
> If you want to use F2fs a custom mounting script would be needed. Not sure about F2fs I didn't try those externally

Well, generally I am quite familiar with the insides of the unix-like systems such as BSD and Linux ones, and with all that knowledge I can say that android is a huge mess…
