### ISSUE TITLE
Camera & Flash light Bug

### ISSUE THREAD

**Issue by NoRRt** [ananjaser1211/FloydQ_Reports#157]
Flash Light Not Work :" https://i.paste.pics/760a6b6c53f38269a7ae7039d8d67353.png
Sometimes the camera app does not work : https://i.paste.pics/d656bf8abf432b84566654da9d4f35e5.png

**Comment by ananjaser1211** [comment]
this is #140 i have clarified the title to avoid duplicates, it is the same issue that is breaking your flashlight / camera
the only available fix right now is a reboot
