### ISSUE TITLE
[LAG] Google Chrome is having a lot scroll lag!

### ISSUE THREAD

**Issue by HollowayFox** [ananjaser1211/FloydQ_Reports#159]
This is not very important but, I didn't find a resolution for that

**Comment by ananjaser1211** [comment]
This is not a ROM issue, but an issue with webview, some OEMs have fixed it, samsung did not yet. i face the same issue on my unrooted , stock galaxy S9+. any thing that uses webview just freezes after a while. this includes chrome.

so wait until samsung releases a fix and then ill integrate it in V4. assuming they fix it

More info here : https://www.reddit.com/r/Galaxy_S20/comments/hllof2/chrome_freezing_s20_5g_exynos/
