### ISSUE TITLE
[BUG] Keylight not lighting up correctly

### ISSUE THREAD

**Issue by aladie** [ananjaser1211/FloydQ_Reports#16]
**Describe the bug**
The LEDs of the back button and app-switcher seem only to light up when the phone is unlocked and not when pressed.

**To Reproduce**
Simply use the buttons and try for yourself.

**Expected behavior**
The buttons lighting up when pressed.

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
Moved to #102
