### ISSUE TITLE
[BUG] Update?

### ISSUE THREAD

**Issue by SmartBoy84** [ananjaser1211/FloydQ_Reports#162]
**Describe the bug**
How do I update?

**Expected behavior**
Online updates, seamless?

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
How do I update the rom and kernel? Do I have to reinstall and keep checking the xda page?

**Comment by ananjaser1211** [comment]
There is no "OTA" support, i dont have the infrastructure to run and host seamless updates. when a version is available, it will be announced on XDA and my telegram group, which then you download and install as per provided instructions (i.e dirty flashing the new rom.zip) aslong as you are coming from V3 > V4 you dont need to format, unless it was mentioned to do so

**Comment by SmartBoy84** [comment]
So the *unreleased(?) v4 will not require me to format?
I can just download the rom, deselect all the options as those will already exist and effectively update?

**Comment by ananjaser1211** [comment]
> So the *unreleased(?) v4 will not require me to format?
> I can just download the rom, deselect all the options as those will already exist and effectively update?

Pretty much, right now i dont see any reason you need to "wipe data" to update to V4. if that changed ill be sure to mention it in the thread, but android Q is more forgiving to this compared to oreo / pie and so on.

you ofcourse need to re-select the features you need and select "no wipe" in the aroma menu, the zip will format what it needs and install the update

**Comment by SmartBoy84** [comment]
'need to'?
V4 has been released?

**Comment by ananjaser1211** [comment]
@SmartBoy84 Not yet. but when it is basically.

**Comment by SmartBoy84** [comment]
Woah.
I was expecting the s7 edge to get upto 10 but 11 as well?
If it can be done, that would be amazing!

**Comment by ananjaser1211** [comment]
V4 is still Android 10 Oneui 2.1

OneUI R is still far. i will do try to port it when its available

**Comment by SmartBoy84** [comment]
Oh, opps
Regardless, amazing job on this dev! :)
