### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SmartBoy84** [ananjaser1211/FloydQ_Reports#163]
**Describe the bug**
I can't swipe to type.

**To Reproduce**
1. Try to type by swiping

**Expected behavior**
I expected it to behave like the stock type to swipe

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Comment by ananjaser1211** [comment]
did you download your language > swipe,touch and feedback > keyboard swipe controls > swipe to type ?

cuz it works just fine here

**Comment by SmartBoy84** [comment]
Sorry, I didn't do that - It works now!
;P

**Comment by ananjaser1211** [comment]
Perfect
