### ISSUE TITLE
[BUG] ROM made by the wrong person

### ISSUE THREAD

**Issue by Lunarixus** [ananjaser1211/FloydQ_Reports#164]
Yeah so this ROM was made by AnanJaser1211 which is invalid, the ROM was actually made by corsicuntanu, disgustan.

**Comment by ananjaser1211** [comment]
sed -i 's/corsicuntanu/anandjesser1321/g' rom.zip

**Comment by souzajerry** [comment]
gave this mimimi, on xda itself anan said: "This ROM is made with heavy collaboration from @corsicanu make sure to give him coffee" anan for me you don’t even need to explain yourself, continue this magnificent job you’re doing, you’re awesome. sorry for my bad English

**Comment by ananjaser1211** [comment]
@souzajerry it is just banter, i know the dude. dont worry about it

**Comment by corsicanu** [comment]
> Yeah so this ROM was made by AnanJaser1211 which is invalid, the ROM was actually made by corsicuntanu, disgustan.

Totally agree with you.. Shaking my smh

**Comment by souzajerry** [comment]
sorry I didn't know but I don't like people like that but that's ok, thanks for explaining

**Comment by souzajerry** [comment]
I really liked the work of you two but I am too young to contribute financially but I am always here to support and defend you but sorry I didn’t know it was just a joke and again sorry for my bad English

**Comment by ananjaser1211** [comment]
@souzajerry All good mate. appreciated
