### ISSUE TITLE
Nethunter? [Request]

### ISSUE THREAD

**Issue by SmartBoy84** [ananjaser1211/FloydQ_Reports#166]
Is there anyway I can get Kali Nethunter installed alongside this?
I have a vague recollection that it required a seperate kernel.

**Comment by ananjaser1211** [comment]
It does need a seperate kernel and there is already a fork of morokernel that supports it here and Android Q https://forum.xda-developers.com/s7-edge/development/kernel-wirusmod-t3943474/

I personally won't add nethunter support to cronos as i have to alter the kernel significantly
