### ISSUE TITLE
[BUG] Broken on PiP (Picture in Picture feature)

### ISSUE THREAD

**Issue by mclongthanh** [ananjaser1211/FloydQ_Reports#167]
Note FE (N935F/DF)
* Stop running video in picture-in-picture mode and cannot re-size to fullscreen after using for a while
* Sometimes lag when using full gesture system insteads of hard button while surfing the lastest chrome browser

**Comment by SypeR54** [comment]
@mclongthanh Tested on S7 Flat G930F, International variant.

ROM: FloydQ v4 (internal test release)
Kernel: CronosKernel V5.5 (internal test release)

- Non-stop 30min continous video playback in PiP mode via YouTube Vanced app. No issues so far. Tested Start/Stop, fullscreen, returned normal app state... All functions works good. Logcat doesn't report anything wrong.
- Navigation bar issue is releated with Google's Chrome app features. Chrome has side fast swipe tracker for switching tabs fastly. Probably full screen gestures and Chrome's gesture overlaps and it can't decide which one is which. Please try your same daily usage on another browser (like Samsung Browser or Microsoft Edge Mobile)

**Comment by ananjaser1211** [comment]
Watched a full podcast (2hr) in latest YouTube vanced with PiP and the issue never surfaced.

This might be due to outdated YouTube Vance if you used the one from the ROM.

In any case, the next release will include the updated one.

**Comment by mclongthanh** [comment]
Thanks for your info.
I believe that those I mentioned above is chromium issue: https://github.com/ananjaser1211/FloydQ_Reports/issues/159
video frame (PiP mode) was broken on chrome, not youtube vanced; and gesture was lag due to using chrome
I've tried enable GPU backlist but nothing change for me
This chromium issue cause the battery drain quickly, and phone was getting too hot
I've tried some different versions of chromium, and get stable at version 78 or 77, also battery save well, phone isn't hot
I think someone said the Rom is heavy related to this chromium-webview issue, then they got draining and hot problem
