### ISSUE TITLE
[BUG] Broken S Pen and Air Command Functionality 

### ISSUE THREAD

**Issue by SypeR54** [ananjaser1211/FloydQ_Reports#168]
**Describe the bug**
Our testers dedects S Pen and Air Command is broken on latest official release (V3) and latest test release (V4). 

**To Reproduce**
There is a couple of ways to reproduce the bug.

> **Alternate Way 1:**
>1. Go to "Settings > Advanced Features > S Pen"
>2. Click on "When S Pen is removed"
>3. Set it as "Open Air Command"
>4. Detach your S Pen from device.
>5. See and log the error.

> **Alternate Way 2:**
>1. Detach your S Pen from device.
>2. Hover the pen over screen.
>3. Click the "S Pen button"
>4. See and log the error.

> **Alternate Way 3:**
>1. Go to "Settings > Advanced Features > S Pen"
>2. Enable "Screen-off Memo" feature
>3. Turn off your phone screen.
>4. Detach your S Pen from device.
>5. See and log the error.

**Expected behavior**
With "Way 1" and "Way 2" must be show Samsung's Air Command menu (check screenshot 1 and 2) and "Way 3" must be show Samsung's Screen-off Memo feature to writing memos/notes.

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/12627005/90313302-3fbe5680-df14-11ea-9daf-a5e3030f2d1e.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/12627005/90313355-8ca22d00-df14-11ea-8705-adcdcefb4533.png)
Screenshot 3:
![image](https://user-images.githubusercontent.com/12627005/90313389-dab73080-df14-11ea-8292-59613c63302a.png)

**Affected Smartphone:**
 - **Device:** Galaxy Note 7 BE and FE
 - **Model:** N930F and N935F

**Additional context**
- We already have internal testing logs. But if anyone wants to contribute, please reach us.

**Comment by sht2017** [comment]
Still having this problem on 6.0 ;(

**Comment by ananjaser1211** [comment]
@sht2017 Do not update the included samsung notes app, when you do, it installs 18.5:9 App due to prop name, we can only use 16:9 app

uninstall all updates, and do not le it auto-update. will work then

**Comment by sht2017** [comment]
@ananjaser1211  I found a solution. You could use some applications to spoof model, device ID, etc on google play store and google play service. Then update samsung notes via google play. And then you'll get a samsung notes in 16:9.

**Comment by sht2017** [comment]
By the way, spoof on samsung application store won't be work in this case.
