### ISSUE TITLE
[Feature] Face unlock

### ISSUE THREAD

**Issue by oopsitsdeleted** [ananjaser1211/FloydQ_Reports#169]
**Describe the feature**
Have a feature where you can use your face to unlock your device 

**Possible Visualization**
Example ways to visualizate the request:
1. Find a screenshot of feature
2. Capture a video screenshot of feature
3. Draw a concept of feature
4. or... be creative :)

**Expected behavior**
A clear description of what you expected to happen
. Turn on your phone and look at the phone to unlock it

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device: [e.g. Galaxy Note 7 BE]
 - Model: [e.g. N930F]

**Origin of Feature**
- Add feature of origin device brand, device model and (if its possible) firmware link.
I found face unlock on the pixel experience plus rom. the setting was in the main settings page and not in smart lock. so it might be possible to be able to use the S9's face unlock option go into a different screen for face unlock.

**Comment by SkyrilHD** [comment]
Hi,

Actually, Anan tried porting it too but it was failing at scanning (because it can't load mcregistry blob) , so he gave up on Face Unlock.

If you talk about Google's Smart Lock 'Trusted Face' feature, it got removed by Google since Android 10 (iirc)

**Comment by oopsitsdeleted** [comment]
> Hi,
> 
> Actually, Anan tried porting it too but it was failing at scanning (because it can't load mcregistry blob) , so he gave up on Face Unlock.
> 
> If you talk about Google's Smart Lock 'Trusted Face' feature, it got removed by Google since Android 10 (iirc)

oof

**Comment by SypeR54** [comment]
As @SkyrilHD said, Anan tried to port it but because of our old Oreo mcRegistry blob, we can't use the whole security features of Android 9 and 10. 

With Android 10, Google removed their own "Trusted Face" face unlock method because of "doesn't provide enough security on old/low-end devices".

Until we find a proper way to port mcRegistry blobs to fully work on Android 10 OS, we can't use any "native" face unlock method sadly. Also this porting sitution isn't possible in the near future. So i mark this request as "wont fix".

**Comment by arkgnan** [comment]
Is it safe to remove iris & face apk on system app (I forget the package name) but it's in there (v2)

**Comment by SypeR54** [comment]
@arkgnan There is already released V3 and also V4 is on the way. Feel free to remove Iris and Face apk if you're using S7 or S7E.

**Comment by ananjaser1211** [comment]
> Is it safe to remove iris & face apk on system app (I forget the package name) but it's in there (v2)

This will make the Security tab / biometrics take ~5 seconds or more to load.

**Comment by patsonator** [comment]
@ananjaser1211 Air Command don't work on V4 and the Iris option is missing in settings.

**Comment by ananjaser1211** [comment]
This feature wont be implemented ever. closing
