### ISSUE TITLE
[Request] note fan edition port, n935k

### ISSUE THREAD

**Issue by rfreshlei** [ananjaser1211/FloydQ_Reports#17]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by aladie** [comment]
To my understanding the SM-N935F has the same soc (Exynos 8890) as the galaxy s7 so just try flashing the rom like the dude in this Video: https://youtu.be/AOQSyQf5RXg

I don't take any responsability if anything bad happens to your phone.

**Comment by rfreshlei** [comment]
Have anybody tried ? Are we going to release this ROM officially for NFE?

**Comment by ananjaser1211** [comment]
An official Note FE version of this ROM will come once the S7.S7E versions are a bit more stable.

Yes it is planned.

**Comment by rfreshlei** [comment]
@ananjaser1211 thanks a lot for making this fantastic ONEUI 2.0 ROM for NFE
Can I know if this V2 rom support N935K ?

**Comment by SkyrilHD** [comment]
Well, if you follow the newsletter channel, then you would know.

P.S : This version has very experimental Note 7 FE support. Let me know if it works or not, if it does, Iris probably wont work.

**Comment by rfreshlei** [comment]
I saw this information from news channel and it is little confusing to me as it does not say if it support 935K/L/S model even they share the same chipset with N935F,
