### ISSUE TITLE
[Feature] Disable capacitive button in certain apps / mode (landscape) 

### ISSUE THREAD

**Issue by Switchof** [ananjaser1211/FloydQ_Reports#173]
**Describe the feature**

Toggle/option to disable capacitive button  in certain apps/mode for those using navbar/gestures.This isn't related to no navbar/gestures user.This is little useful rather disable capacitive buttons totally.

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device: Galaxy S7E
 - Model: G935F

**Origin of Feature**
- Add feature of origin device brand, device model and (if its possible) firmware link.

**Comment by ananjaser1211** [comment]
This is not within the scope of this project. You are asking for a full custom APP that disables buttons on command. Not something I can do or a standard function in Samsung ROMs.

What you could do is use gametools to disable those keys in games. For other use cases (video?) Use the button lock feature.

Anything else will have to just not touch the buttons
