### ISSUE TITLE
[Feature] QHD (60 fps) resolution option in camera 

### ISSUE THREAD

**Issue by LongChicken** [ananjaser1211/FloydQ_Reports#175]
The title speaks for itself. An option to record video in QHD 2560×1440 resolution with 60 fps mode enabled using the stock Samsung camera.

**Smartphone**
 - Device: Galaxy S7 Edge
 - Model: G935F

**Comment by ananjaser1211** [comment]
I don't think the Samsung camera apk has an entry for 1440P_60 . So not sure if this can be done or not.

@cvolton thoughts ?

**Comment by Cvolton** [comment]
new entries can be modded into the apk relatively easily

**Comment by ananjaser1211** [comment]
@Cvolton Alright thanks. Let's see

**Comment by ananjaser1211** [comment]
I forgot to include this in the released rom. patch here https://github.com/ananjaser1211/FloydQ_Reports/issues/213
