### ISSUE TITLE
[BUG] 3rdParty Calls Cant reduce volume properly (Sounds loud on lowest setting)

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#176]
**Describe the bug**
When using calls via WhatsApp , Imo And other 3rd party apps (That use the "communication calls" path) you cant reduce the volume properly, when you lower it, it still sounds very loud

**To Reproduce**
1. Start a 3rd party call
2. Try to adjust volume
3. volume slider changes, but does not reflect the audio level

**Additional context**
- Issue possibly related to `vc_call_vol_steps` which has been an issue in Pie, however a fix was available due to the availability of N7FE PIE base. another approach to fix the issue is needed and being worked on.
- This issue could be the cause for the Audio Muting issue #123 as it breaks Routing during these calls. and the muting issue happens often when using whatsapp calls as discovered by testers early on

**Comment by ananjaser1211** [comment]
Well this did not take long, Patch for the issue is available, reported to work by 2 so far. when reducing volume, it is quiet and when its increased to max it is loud. Flash in TWRP

[AudioPatch.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/5151328/AudioPatch.zip)

P.S : This Also needs to be tested for the AudioMute bug, as it might fix it too. waiting on results anyhow

**Comment by SypeR54** [comment]
Due to new fixes included in V5, i'm closing the bugs and marked as "Addressed". Thanks for your report, effort and help.

**Comment by eddykeys** [comment]
My phone still goes silent even after flashing the audiofix file i have to always restart. Please is there any workaround to fix this issue am using S7 edge exynos
