### ISSUE TITLE
[BUG] Note7/Note7 FE shows Optimizing Apps every Boot

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#177]
**Describe the bug**
As title points

**To Reproduce**
Reboot the device

**Smartphone (please complete the following information):**
- Galaxy Note 7 FE and Note 7 BE

**Additional context**
- This is due to SMPS s-pen framework that is broken.

**Comment by ananjaser1211** [comment]
[AppOptimizingFix.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/5151382/AppOptimizingFix.zip)

This will disable the problematic S-PEN framework and fix the issue.

**Comment by arkgnan** [comment]
> [AppOptimizingPatch.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/5151408/AppOptimizingPatch.zip)
> 
> This will disable the problematic S-PEN framework and fix the issue.

this patch only for N7, am I right? so, if my device is S7, I don't need to flash those patch

**Comment by ananjaser1211** [comment]
> > [AppOptimizingPatch.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/5151408/AppOptimizingPatch.zip)
> > This will disable the problematic S-PEN framework and fix the issue.
> 
> this patch only for N7, am I right? so, if my device is S7, I don't need to flash those patch

Correct, it wont install on S7/S7E , and only on Note7 and note7FE

**Comment by SypeR54** [comment]
Due to new fixes included in V5, i'm closing the bugs and marked as "Addressed". Thanks for your report, effort and help.
