### ISSUE TITLE
[BUG] ARStickers not showing up in camera after selecting it in Aroma

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#178]
**Additional context**
- This is due to a mistake in the ROMs installation script . that does not extract the correct feature file. whoops

**Comment by ananjaser1211** [comment]
[ARStickersPatch.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/5151422/ARStickersPatch.zip)

This patch will enable ARStickers, Be sure to flash it ONLY if you selected AR Stickers in AROMA, otherwise it wont work

**Comment by ananjaser1211** [comment]
ARStickerPack patch has been updated, to include the APKs since some forget to pick it up in aroma.
also might have fixed a logic issue that caused install issues on some twrps

[ARStickersFULL](https://drive.google.com/file/d/18V2s1R0B-gS9dol9yQ1lXAgMhc2QIdsA/view?usp=sharing)

**Comment by SypeR54** [comment]
Due to new fixes included in V5, i'm closing the bugs and marked as "Addressed". Thanks for your report, effort and help.
