### ISSUE TITLE
[BUG] 1120 Fonts Mod Missing even when selected

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#180]
**Describe the bug**
The modded SamsungSans APK is not properly installed

**Smartphone (please complete the following information):**
 - All

**Additional context**
- This is caused by selecting BOTH google product sans AND 1120 fonts mod. Both custom APKs use the same base apk to add custom fonts. the script needs to be fixed to only install product sans, if 1120 was not selected.

**Comment by ananjaser1211** [comment]
This patch should resolve the issue, delete the single productSans apk (google font) and replace it with the 1120 fonts pack which also includes the google font


Download : [GoogleDrive ](https://drive.google.com/file/d/1ri6P6BUJnjzYIK6AlK40UmArbAupf1Wc/view?usp=sharing)(File too large for git)

**Comment by SypeR54** [comment]
Due to new fixes included in V5, i'm closing the bugs and marked as "Addressed". Thanks for your report, effort and help.
