### ISSUE TITLE
[BUG] Compass is not accurate

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#181]
**Describe the bug**
The compass in maps never point to the right direction

**To Reproduce**
1. open compass in maps
2. do 8 figure calibration
3. notice it is still not calibrated and reading is backwards

**Screenshots** Thanks @DaveSouthUK
![photo_2020-09-01_23-25-57](https://user-images.githubusercontent.com/25624482/91939372-92389a80-ecaa-11ea-8fc6-9ca1da23aec7.jpg)

The blue device is running Q with N7FE sensors blob
the black one is running BD Pie port with S7 sensors blob

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7/S7E]
 - Model: [e.g. G93xF]

**Additional context**
- we use the note 7 Sensor blobs to have working sensors, as S7 ones are from oreo, and they crash the whole system on Q (they work fine on Pie). They are identical except that, the N7 compass / mag sensor or whatever it is called, is sorta mounted upside down in the device. so when your phone is pointing up, the sensor data is actually upside down at an angle.

Few possible workarounds.

1) Figure out how i had S7 Oreo sensors working back in December on S9 BETA Q. as that did NOT have the compass issue

2) Figure out a way to reverse compass read outs via the kernel ?? dunno

3) Shim our sensor and ditch the N7FE one ? also dunno

**Comment by ryu075** [comment]
Hello

I would like to help fix this bug
how can I do it?
I am fond of drones and I need the compass of my S7 to work perfectly and I would also like to enjoy android 10 on my mobile

Thank you for all of your work

a greeting

**Comment by ananjaser1211** [comment]
@ryu075 Unless you can write a shim to make s7 sensor blobs work on Q. There isn't much you can do

I can't yet

**Comment by ryu075** [comment]
Thanks for your attention, I'm waiting for you to do it to install android 10 on my s7, for now I need my compass, if there is something I can do, you just have to ask
a greeting

**Comment by ananjaser1211** [comment]
@ryu075 Thank you. I'll be in touch for tests once I can figure something out

**Comment by ananjaser1211** [comment]
This bug will be fixed in V8. 3 years later... lol. we got the stock sensors loading and working on S7

![photo_2023-10-20_20-45-36](https://github.com/ananjaser1211/FloydQ_Reports/assets/25624482/c6950463-d5e0-4696-9929-d41a13dc9d19)

**Comment by ananjaser1211** [comment]
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172
