### ISSUE TITLE
[BUG] Camera crashes during video calls (Whatsapp, Duo)

### ISSUE THREAD

**Issue by jiyojolly** [ananjaser1211/FloydQ_Reports#182]
**Describe the bug**
The camera crashes and stops working during video calls (WhatsApp, Duo, etc.). The issue persists until the phone restarts. 
Both apps show error messages saying 'Device camera has stopped working. Please restart the phone...'
The main camera app (for photography) still works with no issues though.

**To Reproduce**
1. Make video call using any video calling app (WhatsApp or Duo)
2. Continue call for 5 - 10 mins.
3. Camera crashes sometimes showing green background
4. Further attempts at video calls show 'camera not responding' error

**Expected behavior**
Normal video calls using any popular video calling apps

**Screenshots**
None 

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model: 935FD

**Additional context**
None.

**Comment by ananjaser1211** [comment]
Can you please start logging until it crashes. we had one report of this bug but we are unable to recreate it at all on whatsapp or imo with calls upto 30 mins sessions

**Comment by jiyojolly** [comment]
Since it is very random, I will try my best to grab a log.

**Comment by ananjaser1211** [comment]
> Since it is very random, I will try my best to grab a log.

Can you download AIDA64 And send a screen shot from the devices tab (the one that shows what camera sensor you have)

On V3 or V4 it's fine

**Comment by jiyojolly** [comment]
I managed to grab some logs.
[logcat_09-03-2020_08-41-22.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/5166430/logcat_09-03-2020_08-41-22.txt)

**Comment by kathir28** [comment]
This behaviour also happends when using snapchat (green camera or black)

**Comment by arkgnan** [comment]
i get same issue, green camera when use whatsapp video call, and it happen randomly

**Comment by SkyrilHD** [comment]
How long do you have to video call to have a green camera? Because when I tried to reproduce this issue, I video called myself for nearly 35 minutes and couldn't reproduce it.

I will try video calling myself again today and see if I can reproduce it

**Comment by arkgnan** [comment]
> How long do you have to video call to have a green camera? Because when I tried to reproduce this issue, I video called myself for nearly 35 minutes and couldn't reproduce it.
> 
> I will try video calling myself again today and see if I can reproduce it

only 5-10 minutes

**Comment by arkgnan** [comment]
When it happen, I must restart my phone to make the camera work again on video call. Close the app (whatsapp) don't make any difference. And I get this issue only in v4

**Comment by arkgnan** [comment]
I don't have log, but I hope this screenshot can explain the issue
![20200925_194948](https://user-images.githubusercontent.com/17277219/94269149-73a38780-ff68-11ea-8337-355bbb6280c8.jpg)

**Comment by kathir28** [comment]
[camera.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/5286509/camera.txt)

Here's a log

**Comment by matinzd** [comment]
+1
![20200928_103427](https://user-images.githubusercontent.com/24797481/94400562-357bb300-0176-11eb-83b0-f38b1747ac3f.jpg)

**Comment by Sora0605** [comment]
Hello,

I've got same issue on S7 flat, Floyd V4.0, after 10 minutes: video flux freeze, became dark, then black, then green. And the other user in the videocall have a message "poor connection" instead of my video.

Then, msut restart the phone to re-activate the video call ability.

**Comment by SypeR54** [comment]
@Sora0605 As i tested over hours of calls, it only crashed if battery cant supply the camera hardware to process data. Unless it works fine. Can you check your battery amount?

**Comment by matinzd** [comment]
I had this problem even I had 90% of battery and that does nothing to do with the battery. I think kernel is the problem because I had this issue on AOSP Q rom too and only on Q version @SypeR54. It is random sometimes it crashes after 1 hour even with low amount of battery and some times after 5 minutes with high amount of battery. This is so fraustraiting and I don't know why @ananjaser1211 did not pin the issue!

**Comment by Sora0605** [comment]
> @Sora0605 As i tested over hours of calls, it only crashed if battery cant supply the camera hardware to process data. Unless it works fine. Can you check your battery amount?

Hello,
We were 3 users videocalling. 
At start of the call, battery was about approximately 53%.
At end of the call, battery was about approximately 40%
Total duration of the call was 28'40'', but after 10' approximately my video flux has stopped. I stayed online, only with the audio flux until end of call.

**Comment by arkgnan** [comment]
I think this is critical issue. I know you and all tester didn't get this issue. but now, more user say get this. and it is random. most of the comment in this issue report is S7 Flat. and yes, its make us frustrating. please make more attention for this issue before release new version

**Comment by Sora0605** [comment]
> @Sora0605 As i tested over hours of calls, it only crashed if battery cant supply the camera hardware to process data. Unless it works fine. Can you check your battery amount?

Hello,
We were 3 users videocalling. 
At start of the call, battery was about approximately 53%.
At end of the call, battery was about approximately 40%
Total duration of the call was 28'40'', but after 10' approximately my video flux has stopped. I stayed online, only with the audio flux until end of call.

**Comment by ananjaser1211** [comment]
> I had this problem even I had 90% of battery and that does nothing to do with the battery. I think the kernel is the problem because I had this issue on AOSP Q Rom too and only on Q version @SypeR54. It is random sometimes it crashes after 1 hour even with a low amount of battery and sometimes after 5 minutes with a high amount of battery. This is so frustrating and I don't know why @ananjaser1211 did not pin the issue! I have this issue on S7 Edge.

It is related to the FDSAN patch that was applied in V4. Didn't pin as a fix exists. But not one that suites me. It will bring back the random camera crash from before

A temporary solution is to copy rom.zip/floyd/vendor/lib/libexynoscamera3.so (and the one in lib64)

Under the same path in 4

**Comment by matinzd** [comment]
> > I had this problem even I had 90% of battery and that does nothing to do with the battery. I think the kernel is the problem because I had this issue on AOSP Q Rom too and only on Q version @SypeR54. It is random sometimes it crashes after 1 hour even with a low amount of battery and sometimes after 5 minutes with a high amount of battery. This is so frustrating and I don't know why @ananjaser1211 did not pin the issue! I have this issue on S7 Edge.
> 
> It is related to the FDSAN patch that was applied in V4. Didn't pin as a fix exists. But not one that suites me. It will bring back the random camera crash from before
> 
> A temporary solution is to copy rom.zip/floyd/vendor/lib/libexynoscamera3.so (and the one in lib64)
> 
> Under the same path in 4

Copy where? Could you please explain more?
Again I had this issue on lineage os 17.1 too.

**Comment by ananjaser1211** [comment]
> > > I had this problem even I had 90% of battery and that does nothing to do with the battery. I think the kernel is the problem because I had this issue on AOSP Q Rom too and only on Q version @SypeR54. It is random sometimes it crashes after 1 hour even with a low amount of battery and sometimes after 5 minutes with a high amount of battery. This is so frustrating and I don't know why @ananjaser1211 did not pin the issue! I have this issue on S7 Edge.
> > 
> > 
> > It is related to the FDSAN patch that was applied in V4. Didn't pin as a fix exists. But not one that suites me. It will bring back the random camera crash from before
> > A temporary solution is to copy rom.zip/floyd/vendor/lib/libexynoscamera3.so (and the one in lib64)
> > Under the same path in 4
> 
> Copy where? Could you please explain more?
> Again I had this issue on lineage os 17.1 too.

copy it to either floydv4zip/floyd/vendor/lib (do the same for lib64)

or in twrp copy it to `/system/system/vendor/lib/` 

it exists in lineage 17 too because we use the same patch for the FDSAN crash, which fixes a bug but causes this bug too.

**Comment by arkgnan** [comment]
> > I had this problem even I had 90% of battery and that does nothing to do with the battery. I think the kernel is the problem because I had this issue on AOSP Q Rom too and only on Q version @SypeR54. It is random sometimes it crashes after 1 hour even with a low amount of battery and sometimes after 5 minutes with a high amount of battery. This is so frustrating and I don't know why @ananjaser1211 did not pin the issue! I have this issue on S7 Edge.
> 
> It is related to the FDSAN patch that was applied in V4. Didn't pin as a fix exists. But not one that suites me. It will bring back the random camera crash from before
> 
> A temporary solution is to copy rom.zip/floyd/vendor/lib/libexynoscamera3.so (and the one in lib64)
> 
> Under the same path in 4

If I do that temp solution, is that me get previous camera issue?

**Comment by ananjaser1211** [comment]
> > > I had this problem even I had 90% of battery and that does nothing to do with the battery. I think the kernel is the problem because I had this issue on AOSP Q Rom too and only on Q version @SypeR54. It is random sometimes it crashes after 1 hour even with a low amount of battery and sometimes after 5 minutes with a high amount of battery. This is so frustrating and I don't know why @ananjaser1211 did not pin the issue! I have this issue on S7 Edge.
> > 
> > It is related to the FDSAN patch that was applied in V4. Didn't pin as a fix exists. But not one that suites me. It will bring back the random camera crash from before
> > 
> > A temporary solution is to copy rom.zip/floyd/vendor/lib/libexynoscamera3.so (and the one in lib64)
> > 
> > Under the same path in 4
> 
> If I do that temp solution, is that me get previous camera issue?

It will give you the old issue where the camera would stop working after ~12 hours of uptime approximately and require a reboot.

Which also accelerates if you use the camera more often. So your usage will vary

**Comment by irfankhokhar** [comment]
Same problem for me. S7 edge

**Comment by ananjaser1211** [comment]
The green screen video bug will no longer be an issue with V5, however it will bring back #140 most likely

ive added few mitigations for it, so far no reports of fdsan crashes, lets see how it goes
