### ISSUE TITLE
[BUG] Screen timeout not working

### ISSUE THREAD

**Issue by Skyterix1991** [ananjaser1211/FloydQ_Reports#183]
**Describe the bug**
I noticed a while before that something is wrong with screen timeout. I set it to 15 seconds, and two minutes later, the screen still didn't turn off. I also turned on showing touch to make sure my screen isn't just broken somehow, there were no touches. I am currently on fresh v4 install, no dirty flashes. I also restarted my phone to make sure it isn't just a one-time thing.

I think I noticed this issue in v3, but I just now checked it to ensure its present.

**To Reproduce**
1. Go to Settings
2. Go to screen timeout option
3. Set it to 15 seconds
4. Leave the phone for a few minutes
5. The screen will not turn off

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by SkyrilHD** [comment]
Hi,
I just turned my screen timeout to 15 seconds and have no issues on mine... Can you check if there are any preventers or can you try with 30 seconds instead of 15, so just to be sure it isn't because of "the settings app".

**Comment by Skyterix1991** [comment]
> Hi,
> I just turned my screen timeout to 15 seconds and have no issues on mine... Can you check if there are any preventers or can you try with 30 seconds instead of 15, so just to be sure it isn't because of "the settings app".

Just now tested it for 15 seconds and 2 minutes. Also returned to the main screen and still, the screen is not turning off.

**Comment by SypeR54** [comment]
@Skyterix1991 I tried it too right now, and it works as is. After 15 second, screen goes to sleep. However, maybe you're using a 3rd party app to change screen timeout for custom values. If you're not sure then do a clean installation and try again after reboot. If still buggy, then please log it with log_all.bat and send the log here.

Thanks.

**Comment by Skyterix1991** [comment]
> @Skyterix1991 I tried it too right now, and it works as is. After 15 second, screen goes to sleep. However, maybe you're using a 3rd party app to change screen timeout for custom values. If you're not sure then do a clean installation and try again after reboot. If still buggy, then please log it with log_all.bat and send the log here.
> 
> Thanks.

A fresh install isn't an option for me now, so I will close this issue and check if that's a case in the fresh install at a later date, and if it is, I am going to reopen. Thanks for your help.

**Comment by SypeR54** [comment]
@Skyterix1991 Sure, if it happens again feel free to re-open issue ticket. Thanks for your reply. 😊

**Comment by SkyrilHD** [comment]
Could you export your installed apps list?

You could use 'List my Apps' by Onyxbits for that

**Comment by Skyterix1991** [comment]
I think I found out what was causing the issue. One of my EdXposed modules is causing this issue. I will now just have to go one by one and check which one. Again thanks for the help and sorry for the trouble.
