### ISSUE TITLE
[Feature] Selectable All-in-One Aroma Patcher

### ISSUE THREAD

**Issue by SypeR54** [ananjaser1211/FloydQ_Reports#186]
**Describe the feature**
Who had issues with rom, they can basically select patches for ROM from Aroma menu and rest will be done via script.

Example of patch list
- Remove CIDManager (select this only when you had "SIM Card changed, please reboot your device to use your new SIM Card.")
- Audio Gain Boost (select this only when you had lower speaker sound than stock Oreo ROM)
- Enable ARSticker (select this if you selected or forgot the select ARSticker on ROM zip)
- Other stuff
- Etc
- Etc

**Possible Visualization**
Example ways to visualizate the request:
1. Use your imagination skill and imagine Floyd AROMA Installer UI.
2. If you managed to imagine Aroma UI then put menus for patch list
3. Flash it.

**Expected behavior**
Like installing a new rom, you just need the select patches for Floyd ROM.

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device: All 8890 devices
 - Model: Exy8890

**Origin of Feature**
- Note 4 patch zip (again by @ananjaser1211 )

**Comment by Nurersafa** [comment]
What is this

**Comment by SypeR54** [comment]
@Nurersafa It's a flashable zip file like rom zip. But instead it has many fixes inside with Aroma user interface.

Also, since V5 update (under testing right now) all of the V4 fixes applied on V5. So we don't need a separate zip for fixes. Because of this i'm closing the feature request until new confusing fix files published.
