### ISSUE TITLE
[Request] RAM management improvement?

### ISSUE THREAD

**Issue by weebawop** [ananjaser1211/FloydQ_Reports#190]
RAM management on FloydQ is decent (especially compared to other ROMs I've tried where it's impossible to have 2 apps running simultaneously). But I still feel it can be improved. I'm a moderately heavy user, not too much bloatware ie Google app etc and I use Greenify to keep running background apps to a minimum

For example using split screen mode with a browser open constantly causes my launcher to close and have to reload when I press the home button. Same happens when I use GCam for example. And from my observation the free RAM never goes below 800mb, under really heavy use it should be around 400/500mb from my experience on stock 8.0.0

Also when using my browser a lot of the time it can't handle 2 tabs open at once, sliding over to a new tab will force the old one to refresh which is annoying

**Comment by ananjaser1211** [comment]
Honestly not sure how much more it can be improved, the 8890 LMK is a big mess thats been causing issues since Pie, and was only fixed recently

maybe moving to full ZRAM based swap approach might be helpful, i will take a look and see what can be done

**Comment by weebawop** [comment]
Thank you. There's a pie ROM called Hyper-rom on xda and on that ROM the ram management was good (though it had other issues besides RAM), maybe you could dissect it to see how the dev did it?

**Comment by ananjaser1211** [comment]
> Thank you. There's a pie ROM called Hyper-rom on xda and on that ROM the ram management was good (though it had other issues besides RAM), maybe you could dissect it to see how the dev did it?

if i have to guess, it will be similar to the latest BlackDiamond release, with Note 7 FE ram / lmk values in props. ROM Wise there is no other way to adjust ram besides props.

the main issue with the S7 is the LMK driver at the kernel level, which needs a full revisit, especially under Q which uses significantly more resources than pie

**Comment by weebawop** [comment]
You say it's the LMK, does the LMK handle browser tabs? Because the issue also extends to browser tabs in that I can't have more than one tab open at once, even going to overview mode to see what tabs I have open then going back to my old tab makes it reload. Same with opening recent apps (without changing apps, just previewing), will make my open tab crash or refresh

**Comment by weebawop** [comment]
The problem is really really bad now, I feel like V4 aggravated the problem. Like now my edge screen and edge panels keep being booted from memory, I have to go into the settings to restart them individually manually

**Comment by ananjaser1211** [comment]
Do you have any custom tweaks installed ? Any "optimizer" modules ? A different kernel ?

While ram does kill background tasks when it has to (usually few hours or so for me after idle if I have alot of recent apps)

Its no where to the extent of closing a chrome tabs or killing panels

I have my usual suite of apps installed + office 365 and adobe reader. I frequently use the S7 for my online lectures. Usually with my uni portal and google (so 4 tabs) and youtube vanced background playback. Not once did it run out if memory so bad it closed. Would have noticed cuz they are playing back video / audio

The issue you are facing usually happens if you have broken swap or zram and aggressive LMK settings.

Right now my lecture is playing in the background (just to test) I have 1.1GB available ram with chrome using 450MB and I'm scrolling youtube vanced.

So far no aggressive LMK.

**Comment by ananjaser1211** [comment]
just to be sure. I've done a full test. Here is a preview

This is V4.0 with Cronos v5.5

https://youtu.be/c390el4K1z8

Here are the status after uploading the video and posting this (no tab or app has been killed yet)
![Screenshot_20200930-124513_Settings](https://user-images.githubusercontent.com/25624482/94663585-defba980-031a-11eb-8f78-cef8f9783789.jpg)
![Screenshot_20200930-124503_Device care](https://user-images.githubusercontent.com/25624482/94663588-e0c56d00-031a-11eb-90ae-6599cb049f98.jpg)

**Comment by ananjaser1211** [comment]
After trying alot of different configs, i cant seem to produce a better result than the one shared previously

i dont think RAM can be improved any further than V4. if you are getting different results, it is most likely due to some other alteration / kernel
