### ISSUE TITLE
[BUG]keeps saying sim card changer restart phone and if i restart the same issue pops up again

### ISSUE THREAD

**Issue by goliatho** [ananjaser1211/FloydQ_Reports#191]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by SypeR54** [comment]
@goliatho We aware of the issue and patched it in next release. Thanks for noticing. Because of patch, i'm closing the issue.
