### ISSUE TITLE
[BUG] Offline/Online charging mismatch %

### ISSUE THREAD

**Issue by getjonjoed** [ananjaser1211/FloydQ_Reports#196]
**Describe the bug**
i created a github account for this problem and, to be honest, i'm a newbie here, i don't exactly know how to do things here, sorry if i left something unanswered. also, i'm not that good at english so, forgive my vocabulary errors :(

so the problem is, when i charge my phone to 100% while powered on, it drains quite fast, even if it's on standby. the next recharge, i tried charging it again to 100%, i turned it off, charge it via offline charging, and it says 84% even though it said 100% the moment i powered it off. i did charge it up to 100% via offline charging, turned it on, and it stayed at 100% for an hour and a half, after that, it drained fast just like charging to 100% while powered on.

i know one ui can really use a lot of power, but i think this problem can be fixed. i don't know if it's a cause of battery being old, i saw some people have the same problem, and i just want to speak up for it, because this is really causes me a headache.

**To Reproduce**
i did use this rom from 1.0, so from there, you just have to use your phone regularly, charge it while powered on till it says 100%, power it off, continue to charge via offline charging to 100% then turn it on, this time, you'll have infinite battery life, for less than 2 hours of course, then your battery drains drastically. weird, right?

**Expected behavior**
for day to day use, it's good, plus the features and fluidity of the rom, i am amazed by the fact it can run on a 4 year old device, i quite expected it to perform like this at first, since i realized that it shows wrong battery percentage when turned on. from there, i do the same thing (just like at the "to reproduce") to fully charge the phone everytime it drops to 15%.

**Screenshots**
as i said, i don't know how to upload screenshots, and to upload logs, but i tried to provide as much info as i can just to get this bug resolved. forgive me for not providing these.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model: G935F(D?) - it's hero2lte, if i'm wrong, sorry

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

ps: this rom has made a great progress since 1.0, i am very thankful it revived my 4 year old phone to be useful again, even if you can't fix this bug, i will still use this rom, cause this is a very good rom if you want the latest software for your s7 edge. keep it up! ;)

**Comment by ananjaser1211** [comment]
This is indeed a bug, suspected to be the root cause of #7 but there is no clear fix just yet

**Comment by getjonjoed** [comment]
is that so? i remember when i first installed this rom, it also freezed when i charged it overnight, i thought it's just an installation error, so i reflashed the rom, and i didn't get the error ever since, i also turned on the always on display, and turned off the battery led light, and i'm wondering that these solved the freezing problem. thank you for notifying this, this is my first bug report so i'm really not good at this, hahaha! thank you once again, more releases to come!

**Comment by ananjaser1211** [comment]
Dont worry, the report is perfectly fine and valid. sadly #7 is not 100% certain of what triggers it, usually the first clean flash (for a day or two) will crash overnight, then it kinda fixes it self.

weird shit

**Comment by getjonjoed** [comment]
well, i can't do anything but to wait for the fix, hopefully it will get fixed, probably not in v5 but in the near future

**Comment by kavosis** [comment]
Hi, I have an s7 edge with a battery capacity of 3600 mAh 
   I just installed version 5 
   Everything is great and smooth, 
   The only problem is that it charges 16% less, ie instead of 3600 mAh, only 3000 amps are charged. 
 In the previous version, the phone was very hot, but in the new version, the temperature is appropriate. 
 I will report any problems I find 
 Thank you dear friend🙏🌷
