### ISSUE TITLE
[BUG] Issues with the microphone

### ISSUE THREAD

**Issue by meverss** [ananjaser1211/FloydQ_Reports#200]
Since I installed Floydq v4. 0 I'm having issues with microphone on phone calles and recording (with the Camera app and the same with Voice Recorder) 
Sound has a noisy background on recordings and volumen is really low on phone calles (people in the other side barely hear me) 
It's not a hardware problem, cause I restore a backup of BlackDiamond ROM and it works fine...

**Comment by ananjaser1211** [comment]
Logs please and a microphone record sample

**Comment by harddriver** [comment]
https://drive.google.com/file/d/1rpnoVF9PGERUKY-eJkfheLntarqlUTke/view?usp=sharing

**Comment by SkyrilHD** [comment]
@harddriver Upload the log to GitHub or remove asking for permission

**Comment by harddriver** [comment]
ok

**Comment by SypeR54** [comment]
Due to new fixes included in V5, i'm closing the bugs and marked as "Addressed". Thanks for your report, effort and help.
