### ISSUE TITLE
[BUG] When entering the location setting, the app stops

### ISSUE THREAD

**Issue by souzajerry** [ananjaser1211/FloydQ_Reports#203]
Hi anan, 
Every time I enter the localization settings the configuration application stops working, I am sending a print together for you to see better what happens. Sorry my bad english

**Smartphone
 - Device: [Galaxy S7 Edge]
 - Model: [G935F]
![image](https://user-images.githubusercontent.com/66040178/95276879-c57ac600-0822-11eb-8062-c2e2e1253579.png)

**Comment by ananjaser1211** [comment]
Have you debloated or disabled any system Apps ? this does not occur un modified. the location settings opens fine here.

attach log_e

**Comment by souzajerry** [comment]
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5340440/log_e.log)

**Comment by ananjaser1211** [comment]
you have an app called Thunderbird that is FCing or part of GMS, so if you modified any of these or your app is outdated, your error is there

**Comment by souzajerry** [comment]
I only use the zatarabattery module that contains the GMS with it, but this application that you mentioned, I never saw

**Comment by ananjaser1211** [comment]
Try to disable it and see. The crash does happen in a part of GMS
