### ISSUE TITLE
[BUG] SMS Messages can't sent after restoring old database via 3rd party app

### ISSUE THREAD

**Issue by madeit22** [ananjaser1211/FloydQ_Reports#206]
i installed the clean version of this rom and i actually selected THR for iran csc. what is the problem?

**Comment by SypeR54** [comment]
If you mean SMS messages, yes i had that similar issue on my Note 4 when i was switching between LOS and Samsung based ROM's. Unfortunaletly it was a SIM card based bug, it wasn't solved until i switch my carrier. After switching my carrier its starting to work on my all devices.

Anyway if your SIM card can send messages on other devices, then try to plug another on your phone, send some blank message to your broken phone number, shut down the phone and replace with your broken SIM. After that try again to send SMS messages.

**Comment by madeit22** [comment]
> If you mean SMS messages, yes i had that similar issue on my Note 4 when i was switching between LOS and Samsung based ROM's. Unfortunaletly it was a SIM card based bug, it wasn't solved until i switch my carrier. After switching my carrier its starting to work on my all devices.
> 
> Anyway if your SIM card can send messages on other devices, then try to plug another on your phone, send some blank message to your broken phone number, shut down the phone and replace with your broken SIM. After that try again to send SMS messages.

tnx for ur advice i will test it but i think its not a sim problem because my sim was doing fine on ported note fe rom. maybe its because i restored my sms messages from old rom to new one?

**Comment by madeit22** [comment]
> If you mean SMS messages, yes i had that similar issue on my Note 4 when i was switching between LOS and Samsung based ROM's. Unfortunaletly it was a SIM card based bug, it wasn't solved until i switch my carrier. After switching my carrier its starting to work on my all devices.
> 
> Anyway if your SIM card can send messages on other devices, then try to plug another on your phone, send some blank message to your broken phone number, shut down the phone and replace with your broken SIM. After that try again to send SMS messages.

tnx for ur advice i will test it but i think its not a sim problem because my sim was doing fine on ported note fe rom. maybe its because i restored my sms messages from old rom to new one?

**Comment by ananjaser1211** [comment]
You should not restore data like this, use samsung cloud to restore msgs, not 3rd party apps.

this is probbaly why your SMS is broken

**Comment by ananjaser1211** [comment]
THR users reported no such issue, therefore it is probably due to the wrong way of restoring SMS, follow the previous msg on how to restore properly
