### ISSUE TITLE
[BUG] PUBG - Detection problem with in-game touch buttons.

### ISSUE THREAD

**Issue by ArifAGA98** [ananjaser1211/FloydQ_Reports#208]
(BUG) When using the marked (green) movement key, pressing the marked (red) keys disables touch detection of the marked (green) movement key. In other words, the touch sensing of the marked (green) movement button while moving in the game turns off when you click the talk button on the right, the binocular switch button or the jump buttons.
![IMG_20201024_060840_846](https://user-images.githubusercontent.com/71526029/97067078-a28e3700-15c2-11eb-8693-2882401c5dbe.jpg)

**Comment by ananjaser1211** [comment]
this is a hardware issue, the display was swapped with a fake one that does not support multitouch properly. most fake displays have firmwares to only work on oreo

refer to https://github.com/ananjaser1211/FloydQ_Reports/issues/194

the game works just fine on my S7e

**Comment by ArifAGA98** [comment]
But Lineageos 17.1 also works fine.

24 Eki 2020 Cmt 07:03 tarihinde AnanJaser <notifications@github.com> şunu
yazdı:

**Comment by ananjaser1211** [comment]
which is based on oreo drivers / kernel.

refer to the issue you opened before, if its only broken for you. its hardware

**Comment by SypeR54** [comment]
https://play.google.com/store/apps/details?id=com.the511plus.MultiTouchTester

Install this app, put all your fingers on the screen and take screenshot (you can use Bixby or Google Assistant). When you managed to take screenshot, send the screenshot here. It must looks like this.

Screenshot taken from completely original G930F with Floyd V4 ROM. As you can see everything is normal and ROM can dedect my every touch.

![Screenshot_20201024-122211_MultiTouch Tester](https://user-images.githubusercontent.com/12627005/97078298-1563d600-15f4-11eb-8428-4b2a0fb0632a.png)

**Comment by Kique808** [comment]
@SypeR54 Is your screen panel, an original Samsung AMOLED screen panel?

Some fake screens may not be able to detect multi touch, making it an impossible thing.

First try replacing your screen for an original one, if your problem persists, make a but report providing a logcat

**Comment by ArifAGA98** [comment]
Yes, my screen is original.  I have no problems with stock rom and
Lineageos 17.1.

24 Eki 2020 Cmt 12:34 tarihinde Kique808 <notifications@github.com> şunu
yazdı:

**Comment by SypeR54** [comment]
@ArifAGA98 Please add Multitouch app screenshot when you're using Floyd ROM.

Also, Stock ROM and LOS has Oreo drivers. Which is fake displays works on them fine. The issue is, Floyd ROM not using the Oreo touch drivers. Instead using Pie drivers from Galaxy N7FE. However the fake displays can only compatible with Oreo drivers.

**Comment by ananjaser1211** [comment]
Fake TSP is hardcoded to only work on certain firmware.

this is a very common issue with fake replacements.

the issue does not happen on my phone, therfore i cant do anything

**Comment by ArifAGA98** [comment]
I understand, thank you very much for your effort.

25 Eki 2020 Paz 07:57 tarihinde AnanJaser <notifications@github.com> şunu
yazdı:
