### ISSUE TITLE
[BUG] SmartView Low framerate

### ISSUE THREAD

**Issue by jonatan39** [ananjaser1211/FloydQ_Reports#209]
The smart view function has lag at times, with the 8.0 rom it was fluid

**Comment by SypeR54** [comment]
I tried it on V4 and its working good. Some testers also tested on V5 and feature works good too. Be make sure you have enough wireless bandwidth for both device. Because screen mirroring spend some bandwidth (around 100mbps for both device) because of bit rate.

**Comment by ananjaser1211** [comment]
i dont have a point of reference (never used oreo) but it runs at the same framerate as my note 8 and note 5.

so i think i mismarked this one.

**Comment by ananjaser1211** [comment]
Closing this as no further discussion is going on. tested it again on my TV ad it feels fine.
