### ISSUE TITLE
[BUG] Frozen Screen Suspended/unresponsive

### ISSUE THREAD

**Issue by PauloArthur531** [ananjaser1211/FloydQ_Reports#210]
A tela fica congelada quando está suspensa, em 1 mês de uso aconteceu cerca de 4 vezes, ela fica desligada, e quando ligo a tela e deslizo para desbloquear o aparelho ele simplesmente demora muito pra responder, desligo a tela para deslizar novamente e desbloquear o telefone, ao desligar ela não liga novamente e os Botões Home Return, Power entre outros não funcionam ou respondem, se quer acendem, o celular fica travado por cerca de 5m até eu conseguir segurar o botão power por mais de 30s até aparecer o botão de reiniciar o aparelho e ele voltar ao normal.

Translation : The screen is frozen when it is suspended, in 1 month of use it happened about 4 times, it is turned off, and when I turn on the screen and slide to unlock the device it simply takes too long to respond, turn off the screen to slide again and unlock the the phone, when it hangs up, it doesn’t turn on again and the Home Return, Power buttons among others don’t work or respond, if they want to light up, the phone is locked for about 5m until I can hold the power button for more than 30s until the restart the device and it goes back to normal.

**Comment by ananjaser1211** [comment]
Translate this into english.

follow the reporting guide to provide logs of the issue, because i dont have this issue. or testers. this is most likely due to user app issue.

i suggest you clean flash first. update BL/CP. if this is not due to userapp, its a hardware issue.

**Comment by SkyrilHD** [comment]
@PauloArthur531 Hi,

This might be due to infinity wallpapers, since one of our tester also experienced this issue and the current fix/workaround is to set a normal wallpaper.

Also logs would be helpful, so we can look into this issue further.

**Comment by ananjaser1211** [comment]
Cool. thanks for the helpful report
