### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PauloArthur531** [ananjaser1211/FloydQ_Reports#211]
O Celular fica travado enquanto está suspenso

 - Device: [Galaxy S7]
 - Model: [G930F]
 - FloydQ ROM V4.0

Tela suspensa do aparelho fica congelada e aparelho não liga sem motivo aparente, ocorreu cerca de 4x em um mês, botões não respondem durante o bug e o celular não responde a toques, é necessário reiniciar o aparelho para o mesmo voltar ao normal

**Comment by ananjaser1211** [comment]
Duplicate #210
