### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PauloArthur531** [ananjaser1211/FloydQ_Reports#212]
Smart View Sinaliza que o aparelho está conectado na TV porém não compartilha a tela

 - Device: [Galaxy S7]
 - Model: [G930F]
 - FloydQ ROM V4.0

**Comment by ananjaser1211** [comment]
SmartView is working just fine here on my TV and laptop (with microsoft connect app)

bug report needs to be in english + provide logs as required
