### ISSUE TITLE
[BUG]Wifi disconnection issue in version 5

### ISSUE THREAD

**Issue by ArifAGA98** [ananjaser1211/FloydQ_Reports#214]
I did not encounter this problem in version 4, but there are disconnections in wifi in version 5. (Wifi 5ghz)

**Comment by ananjaser1211** [comment]
When WiFI stops loading, run logcat as per the guide and attach it here

**Comment by ArifAGA98** [comment]
I don't know how to do it.

14 Kas 2020 Cmt 10:11 tarihinde AnanJaser <notifications@github.com> şunu
yazdı:

**Comment by ananjaser1211** [comment]
its written in the first page how to take a log. follow it or dont report issues no one else has

**Comment by ArifAGA98** [comment]
Sorry for trying to help you, I won't bother you anymore.

14 Kas 2020 Cmt 17:56 tarihinde AnanJaser <notifications@github.com> şunu
yazdı:

**Comment by ananjaser1211** [comment]
you dont help me by reporting one-off issues that we cant recreate ourselvs.

you can help us by being detailed and logs, otherwise it is impossible for me to figure out what is wrong in your case.
