### ISSUE TITLE
[BUG] Lock screen not opening problem.

### ISSUE THREAD

**Issue by ArifAGA98** [ananjaser1211/FloydQ_Reports#215]
The phone's interface freezes when the screen turns off and does not turn on for about 10 seconds after pressing the power button or home button.  However, restarting the phone resolves the problem.  This issue exists in both version 4 and version 5.

**Comment by oto16** [comment]
> The phone's interface freezes when the screen turns off and does not turn on for about 10 seconds after pressing the power button or home button.  However, restarting the phone resolves the problem.  This issue exists in both version 4 and version 5.

it happened in the oreo stock with me.  must be hardware.

**Comment by SkyrilHD** [comment]
Can you grab a log while you have the freezing issue?

**Comment by ArifAGA98** [comment]
I don't know how to do it.

14 Kas 2020 Cmt 15:19 tarihinde SkyrilHD <notifications@github.com> şunu
yazdı:
