### ISSUE TITLE
[BUG] Video Stabilization is not working

### ISSUE THREAD

**Issue by ihaeseong1** [ananjaser1211/FloydQ_Reports#216]
Yeah... Video Stabilization doesn't work at FloydQ V5. I also flashed the QHD 60fps patch.

But, **I can't use video stabilization at any resolution**.
I resetted the camera app so many times, and there was no changes...

![16053204414987896259432464651368](https://user-images.githubusercontent.com/51202440/99137054-b251e600-266b-11eb-9005-80003106e41d.jpg)
![16053205628718900834891890751263](https://user-images.githubusercontent.com/51202440/99137072-bda51180-266b-11eb-8432-5fdc382b4167.jpg)
![16053206443065861136248812617459](https://user-images.githubusercontent.com/51202440/99137135-ef1ddd00-266b-11eb-8ed5-be3bcc6f9ba5.jpg)

Phone Info
Galaxy S7 Edge (SM-G935S), Installed KOO Csc

I hope there will be a patch soon. Please fix it. Thanks :)

**Comment by ananjaser1211** [comment]
Read #8

EIS is unlikely to ever be fixed on Q
