### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by irfankhokhar** [ananjaser1211/FloydQ_Reports#219]
Dual Messenger auto create many apps.

When I turn on dual messenger for WhatsApp it creates many other dual apps. Like settings, chrome, google play services etc.
![Screenshot_20201121-073214_Settings](https://user-images.githubusercontent.com/67834273/99865705-710e8880-2bcd-11eb-8464-1bf32d2427b5.jpg)
![Screenshot_20201121-073147_Settings](https://user-images.githubusercontent.com/67834273/99865706-7370e280-2bcd-11eb-837a-11bc82265b08.jpg)
![Screenshot_20201121-073116_Settings](https://user-images.githubusercontent.com/67834273/99865707-753aa600-2bcd-11eb-9be0-e5088aaec9bb.jpg)
![Screenshot_20201121-073051_Settings](https://user-images.githubusercontent.com/67834273/99865709-766bd300-2bcd-11eb-91a6-f343151f3602.jpg)

 - Device: [Galaxy S7edge]
 - Model: [SM-G935FD]

**Comment by mathy007** [comment]
@irfankhokhar This is not a bug that's how dual messenger works, even on stock rom

**Comment by irfankhokhar** [comment]
Ok...Thanks  for information

**Comment by ananjaser1211** [comment]
expected behaviour
