### ISSUE TITLE
[PATCH] FloydQ_Patch 3 (3rd Party call volume)

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#220]
~3. This patch is similar to the one from V4 minus some stuff, i am not sure why it is still required as 3rd party volume was resolved. but some people still face volume changing issues.~

~This will fix the volume slider in whatsapp and so on. simply flash it in twrp~

~Download : [3rdpartyvol.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/5577717/3rdpartyvol.zip)~

Do not flash this patch as it is causing more issues than it fixes, follow the bottom workaround to resolve this issue

**Comment by mamduf** [comment]
Hi i flash this patch and crash video call in my phone please help me fix this

**Comment by acharjyanisankh** [comment]
This issue might caused by GOOGLE ASSISTANCE 

try to disable GET HELP FROM GOOGLE in Assistance Device ( Wired headphone ) 

Steps

Open Google app , goto MORE , select GOOGLE ASSISTANCE,  select DEVICES ( Devices that are linked to your assistance) than select the wired headphones and disable GET HELP FROM GOOGLE option 

This would resolve Volume slider issue with thirdparty app

**Comment by ananjaser1211** [comment]
> This issue might caused by GOOGLE ASSISTANCE
> 
> try to disable GET HELP FROM GOOGLE in Assistance Device ( Wired headphone )
> 
> Steps
> 
> Open Google app , goto MORE , select GOOGLE ASSISTANCE, select DEVICES ( Devices that are linked to your assistance) than select the wired headphones and disable GET HELP FROM GOOGLE option
> 
> This would resolve Volume slider/ changing issue with thirdparty app

inttresting, and this fixed it without the patch ?

**Comment by acharjyanisankh** [comment]
Checked with a fresh ROM flash .. idea came to mind while looking at google product forum about volume issue with recent Google app update .

**Comment by acharjyanisankh** [comment]
> > This issue might caused by GOOGLE ASSISTANCE
> > try to disable GET HELP FROM GOOGLE in Assistance Device ( Wired headphone )
> > Steps
> > Open Google app , goto MORE , select GOOGLE ASSISTANCE, select DEVICES ( Devices that are linked to your assistance) than select the wired headphones and disable GET HELP FROM GOOGLE option
> > This would resolve Volume slider/ changing issue with thirdparty app
> 
> inttresting, and this fixed it without the patch ?

Checked with a fresh ROM flash  .. idea came to mind while looking at google product forum about volume issue with recent Google app update ( android 10 based )

**Comment by ananjaser1211** [comment]
This might explain why none of my testers faced it, they , including myself dont use the google app.

**Comment by khaledshabbar** [comment]
I haven't install Google and yet i have the issue with Facebook messenger video calls
