### ISSUE TITLE
[BUG] Can't access camera,  you must restart phone

### ISSUE THREAD

**Issue by jucasowi** [ananjaser1211/FloydQ_Reports#221]
**Describe the bug**
The camera stop working and you must restart the phone.
I saw that if you not open Facebook, tik tok, etc... the camera works. I am not quite sure about that but I think that apk that uses camera makes the error.

**Comment by ananjaser1211** [comment]
Send me your data/log and data/tombstones

**Comment by jucasowi** [comment]
How can I give you that information?

**Comment by ananjaser1211** [comment]
@jucasowi Use fx explorer for example. Grant it root and copy these files.

Assuming the errors where not overwritten the crash might be recorded there.

However in the future whenever this happens. Don't reboot your phone and run logcat_all from the logging kit. More info is on the first page of this report

**Comment by jucasowi** [comment]
I didn't root my phone, because I use it for pay and I am not sure if it works with rooted devide. Is it another way to take the files? like recovery or ADB?

**Comment by ananjaser1211** [comment]
@jucasowi You can copy these files to your sdcard via recovery file manager. In advanced > file manager

**Comment by jucasowi** [comment]
I couldn't found the data/log and data/tombstones. 
The log is attached.

[Log_cat.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/5621571/Log_cat.txt)

**Comment by Eaor** [comment]
I recently had this problem. Here is a screen recording of it happening w/ logs

https://drive.google.com/file/d/1wHhL1inRUCgH635UAv5dYPs6-zWBecOY/view?usp=sharing
[Log_2020-12-06_16-02-32.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/5649547/Log_2020-12-06_16-02-32.txt)

**Comment by ananjaser1211** [comment]
Thanks for the logs.

This is caused by double mutex locks 

     ` #00 pc 000a7e2e  /apex/com.android.runtime/lib/bionic/libc.so (pthread_mutex_lock+6) (BuildId: 51d80220c9e0c42255369657a8641799)`

the patch i made in V5 seems to not fix this fully as seen by `signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c`

i will work on implementing another patch
