### ISSUE TITLE
[Feature]Request to add China mainland CSC(CHC)

### ISSUE THREAD

**Issue by Desomnd** [ananjaser1211/FloydQ_Reports#227]
**Describe the feature**
Request to add CSC of China mainland(CHC).

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device: Galaxy Note FE
 - Model: N935S

**Origin of Feature**
In some Chinese developer's project,the new devices' CSC works well on S7 SERIES/N7/FE with exynos 8890.If you need to know more about these ROMs,I will upload it for you.

**Comment by patsonator** [comment]
@Desomnd Good.

**Comment by ananjaser1211** [comment]
Can you upload Q CHC OMC/ODM package that works ? i dont mind adding it

**Comment by Desomnd** [comment]
@ananjaser1211  Not at home this week... I took it from the rom in my sd card. mega:https://mega.nz/file/vyginJbK

**Comment by SypeR54** [comment]
Link doesnt have the decryption code. Can you re-share the link with decryption code or can you provide the decryption code? Thanks.
