### ISSUE TITLE
[BUG]very low in-call volume

### ISSUE THREAD

**Issue by cardioman82** [ananjaser1211/FloydQ_Reports#231]
When i make a call the incall volume is very low
Recording is always om
Volte enabled
On morokernel latest
S7 edge dual sim...single sim in action now

**Comment by SypeR54** [comment]
@cardioman82 Make sure you have clean installed and dont select any audio mod from Aroma. Then use only ChronosKernel which is ships with this Rom.

And try again. It works fine on all of us.

**Comment by ananjaser1211** [comment]
This might be caused by morosound latest changes which include earpiece modifications.

i dont have this problem currently on cronos v5

**Comment by cardioman82** [comment]
@ananjaser1211 
@SypeR54 
Ok I will revert back to clean install with cronos .
I will let you know if it still exists.

**Comment by cardioman82** [comment]
Call volume is ok now but i faced another problems when i reorder toggle icons in expanded status bar and in launcher they all reset again on restart any resolution for this small problem?
thanks in advance.

**Comment by ananjaser1211** [comment]
Do not pick Extra QS Toggles in aroma to avoid this issue..
