### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by traneson** [ananjaser1211/FloydQ_Reports#232]
I'm facing a problem
Wi fi speed is too low
I have a 30 mb connection
But it's only 4 mb on fast.com and in downloading

**Comment by SkyrilHD** [comment]
Could you gather log? The issue is invalid without it.

**Comment by traneson** [comment]
It works fine now .. but the rom is laggy . I didn't do a factory reset after installing it. Should I? I hope not cause I installed everything

**Comment by SkyrilHD** [comment]
Depends on when you installed the ROM.  If you installed the ROM recently, wait a few hours for all of the caches to be created.

**Comment by traneson** [comment]
Okay I'll wait .. is there an option to zoom out display more. It's on the smallest but still big

**Comment by SkyrilHD** [comment]
You could change the dpi in developer options

**Comment by SypeR54** [comment]
@traneson You should do factory wipe "before" flashing the ROM. If you flashing the rom and "after" doing wipe also same affect like "dirty" flashing.

Be make sure you done the wipe before the flash process.

**Comment by SypeR54** [comment]
@traneson If stock smallest dp setting doesnt satisfied you, go to "Settings > Dev Settings" and find "Minimum screen wide" and put something higher value. For example: 500dp.

Note: DP and DPI values are different things. They are NOT the same. DP value is based on "Distance", DPI is based on "Density".
