### ISSUE TITLE
[BUG]Flash messages turn on screen.

### ISSUE THREAD

**Issue by cardioman82** [ananjaser1211/FloydQ_Reports#234]
when the phone is idle i receive flash messages from my carrier .once the screen is on it will not turn off till i close it from power button or interact  with the message. any ideas about this?
thanks in advance.

**Comment by SypeR54** [comment]
@cardioman82 Its not a bug. As i know, it's called "Emergency Notifications" from carrier. With this feature bustom carrier messages always block the "Screen Timeout". It's same since Android 2.x. Some operators (like Vodafone) sometimes spamming this feature to sell more their "shitty services".

**Comment by cardioman82** [comment]
Thanks for the clarification. ♥
