### ISSUE TITLE
[BUG] "camera shooter sound option" → "shutter"

### ISSUE THREAD

**Issue by endolith** [ananjaser1211/FloydQ_Reports#235]
**Describe the bug**
During the installer, it says "shooter", probably means "shutter".

Not clear if enabling this gives you the option of turning off the camera shutter or enabling it enables the shutter sound?

**Comment by ananjaser1211** [comment]
Correct it is supposed to say shutter.

enabling that option will allow you to enable/disable shutter sound in camera settings
