### ISSUE TITLE
[BUG] fingerprint unlock for apps doesn't work

### ISSUE THREAD

**Issue by tobibrtnr** [ananjaser1211/FloydQ_Reports#237]
**Describe the bug**
In some Apps (e.g. my banking app) you can use your fingerprint to unlock it instead of a password, somehow this doesn't work; the phone unlock by fingerprint however works fine.
Most apps just say that an error occured, one app gave me a "javax.crypto.IllegalBlockSizeException".

**To Reproduce**
1. Install an app that has the feature to unlock by fingerprint
2. Try to activate the fingerprint unlock

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F

**Additional context**
- I tried to log the errors, hope that was the right mode: https://pastebin.com/AUUWxXzV

Thank you!

**Comment by ananjaser1211** [comment]
Duplicate #158
