### ISSUE TITLE
[BUG]Encrypt Device is not Working

### ISSUE THREAD

**Issue by AR-Shanto** [ananjaser1211/FloydQ_Reports#238]
The "encrypt Device" function(Settings>Biometrics and security>Encrypt Device) is not working.

I need to encrypt my device to be able to use my school email. But when I tried to encrypt the phone( yes it's over 90% and charging)  I tapped the Encrypt Device It showed me a screen saying Encrypting but nothing happens after that. I waited over 1-2 hours still showing that screen. I can even click the home button and open everything else on my phone. It's just like a still image showing "encrypting..." but nothing happens 

 - Device: Galaxy S7 edge
 - Model: G935F

**Comment by SkyrilHD** [comment]
duplicate of #198
