### ISSUE TITLE
Clock position reset

### ISSUE THREAD

**Issue by bugger23** [ananjaser1211/FloydQ_Reports#239]
When i Try to move my clock position with SystemUITuner, it will reset to the normal position after a reboot.

I have a SM-G930F

**Comment by SkyrilHD** [comment]
Try moving your clock with QuickStar which is a GoodLock module.

![Screenshot_20210112-001635_QuickStar](https://user-images.githubusercontent.com/28839925/104249431-ae73f180-546b-11eb-85b2-326be012f7f5.jpg)

**Comment by bugger23** [comment]
Oh now its working. Thank you! And btw i want to remap the buttons for a screenshot. How can i do this?

**Comment by SkyrilHD** [comment]
I don't suggest doing that since you will break more of the ROM just to remap the key.

**Comment by bugger23** [comment]
Oh ok, then nevermind. This is by far the vest rom i have ever seen. Keep it up. Youre doing an awesome work.
