### ISSUE TITLE
[BUG] 3rd party calls Volume can't be changed

### ISSUE THREAD

**Issue by bugger23** [ananjaser1211/FloydQ_Reports#240]
By Microsoft Teams, e.g when i'm in a call, i cant adjust the Call Volume.it's on the loudest setting.

**To Reproduce**
1. Go to Microsoft Teams
2. Make a Call
3. See error

Samsung Galaxy S7 - SM-G930F

P.S: i tried the Google app method to fix this, but it didnt work

EDIT : Fully disabling google app / uninstalling it is currently the only way to fully fix this issue

**Comment by SkyrilHD** [comment]
Could you try this?

https://github.com/ananjaser1211/FloydQ_Reports/issues/220#issuecomment-747483319

**Comment by bugger23** [comment]
I was trying that and saw, that no devices are even connected to this assistant.

**Comment by SkyrilHD** [comment]
Could you get a log while pressing the volume buttons and send it here? Anan could look into this.

**Comment by bugger23** [comment]
Sorry, but to the logs, i am a newbie. How can you see the logs?

**Comment by SkyrilHD** [comment]
Start reading from here: https://github.com/ananjaser1211/FloydQ_Reports#how-to-gather-logs-with-loggingkit

log-all is preferred.

**Comment by bugger23** [comment]
[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5803779/log_All.log)

**Comment by bugger23** [comment]
heres another one if the issue isnt listed.
[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5803786/log_All.log)

**Comment by ananjaser1211** [comment]
ideally this would be discussed in #220 but since the patch provided there causes even more issues than it fixes, ill re-mark this as a bug

**Comment by bugger23** [comment]
Oh and Apotheke Thing. I also tested it on WhatsApp and there i cant adjust Volume Call einher. So its most likely a global Problem.

**Comment by bugger23** [comment]
Another*

**Comment by ananjaser1211** [comment]
it basically prevents any 3rd party call app (anything other than simcalls) from working

i wonder tho, could try disabling google app all together. in settings > applications (might need to tick show system app)

if there is no such option, maybe try to not pick google app in aroma. and uninstall it once you boot back up.

because we suspect the culprit in this issue is google app / assistant

**Comment by bugger23** [comment]
No i didnt tick Google app in the Installation. I've installed it manually and took all of the Permissions.I can show you an Screenshot but its in german.
![Screenshot_20210112-203406_Settings](https://user-images.githubusercontent.com/75496677/104363553-a07aab00-5515-11eb-8e9b-d5f81e76d5a1.jpg)
![Screenshot_20210112-203414_Settings](https://user-images.githubusercontent.com/75496677/104363556-a1abd800-5515-11eb-8552-1a22b259999b.jpg)

**Comment by ananjaser1211** [comment]
can you try to temporarily uninstall it ? then reboot the phone and test calls

**Comment by bugger23** [comment]
Nevermind.I tested it without google app and now its working. Thank you

**Comment by ananjaser1211** [comment]
i will keep this open as a workaround for now

**Comment by bugger23** [comment]
Sorry guys to disturb you with this bug again, but now i've had a call on Microsoft Teams and i still cant adjust the Volume. On Whatsapp, its working but not on Teams.
[Uploading log_All.log…]()

**Comment by ananjaser1211** [comment]
Thanks ill take a look, seems that our work around does not work for all apps. bummer

**Comment by bugger23** [comment]
I think i have a tip. When i tried to delete that google app, it had worked in Whatsapp. And after sometime, it didnt worked at all. Maybe its a kind of time based bug?

**Comment by ananjaser1211** [comment]
> I think i have a tip. When i tried to delete that google app, it had worked in Whatsapp. And after sometime, it didnt worked at all. Maybe its a kind of time based bug?
> 
> EDIT: I think this Issue occured because of the Dual Speaker MOD that you can install in the Setup. I think you must patch this MOD.I installed the whole ROM again because of this issue. It must be the Dual Speaker MOD causing this issue.

How certain are you its dual speaker related ? i have testers without dual speaker getting this issue too

**Comment by bugger23** [comment]
It was just a guess. I dont knew you had testers without dual speaker facing this issue.

**Comment by bugger23** [comment]
I found a solution for this issue. You just have to install the Audiopatch from issue #176. It worked at least for me.

**Comment by bugger23** [comment]
I will reopen this so the users can see the solution

**Comment by ananjaser1211** [comment]
ill keep this open, as we wont be using the audio patch from 176, it breaks audio channels and causes issues during some calls. until a better fix is available, this is unsolved

**Comment by bugger23** [comment]
I dont think so. Since i discovered and used this patch, i didnt faced any audio issues at all.

**Comment by ananjaser1211** [comment]
@bugger23 Plug headphones and play on youtube speaker Left Right test

They should be inverted. Some volte / wifi call scenarios echo fully. Hence why the patch is abandoned

**Comment by bugger23** [comment]
I tested it right now and its fully working. The Sound wasnt inverted. And i never faced echo in calls.

**Comment by ananjaser1211** [comment]
interesting, ill flash it later today and see if it gives different results on v5

**Comment by bugger23** [comment]
Oh now i've faced a problem. The Microphone gets really bad in calls even with headphones.

**Comment by bugger23** [comment]
Hello?

**Comment by ananjaser1211** [comment]
The old patch wont be debugged, there is no "easy" way to fix the mass issues it causes

anyway, in V6 whatsapp volume changing (and some other apps) will be working using a new fix, however not all apps will work (telegram for example wont change volume)

**Comment by bugger23** [comment]
Do you already know, when you're releasing V6? I am waiting like 1 or 2 Months for it.

**Comment by ananjaser1211** [comment]
> Do you already know, when you're releasing V6? I am waiting like 1 or 2 Months for it.

No I don't. Everyone is waiting. I'm not a robot

I don't want to release a new update until I fix the audio mute issue. So until I try every fix in my mind, I don't plan on posting an update
