### ISSUE TITLE
SafetyNet not working

### ISSUE THREAD

**Issue by Faiyyaz31** [ananjaser1211/FloydQ_Reports#241]
I'm unable to perform SafetyNet check!
I tried to reinstall certificate but no luck.
Any solution to complete SafetyNet

 - Device: Galaxy S7 Edge
 - Model: G935FD

![Screenshot_20210114-022114](https://user-images.githubusercontent.com/42475448/104511068-31cf4780-5612-11eb-91e6-f8939d019e0e.jpg)
![Screenshot_20210114-022120_Google Play Store](https://user-images.githubusercontent.com/42475448/104511076-33990b00-5612-11eb-8d42-b01c0a07093e.jpg)

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
You modified something. By default only cts will fail
And enabling magisk hide fixes it

Tested.on v5 clean flash just now
