### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bugger23** [ananjaser1211/FloydQ_Reports#242]
Every time when i make a Screenshot, the device recognizes it as a home button press after it takes the screenshot.

1. Make a screenshot

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
have you installed any 3rd party remapping apps ? pressing volume down + power takes screenshots just fine, does not trigger home button.


https://user-images.githubusercontent.com/25624482/104766862-b510aa80-5784-11eb-92b2-45e384008ab2.mp4

**Comment by bugger23** [comment]
Nevermind, i just presses volume down, power and the home button to take a screenshot. I didnt know, that you can just make it wirhout home button
