### ISSUE TITLE
[Feature] Add *Selective Focus* function to Camera

### ISSUE THREAD

**Issue by EliezerB03** [ananjaser1211/FloydQ_Reports#244]
I would like to know if it is possible to add the *Selective Focus* function to the camera in FloydQ for the next version?

The function is in the original Rom, but in this I don't know if they have removed it because it was a problem or for some other specific reason.

** Smartphone
Device: Galaxy S7 Edge
Model: G935F

Greetings to the creator of this excellent rom :)

**Comment by ananjaser1211** [comment]
For now it is not possible, https://github.com/ananjaser1211/FloydQ_Reports/issues/14

both applies to selective focus/live focus and selfie focus

**Comment by ananjaser1211** [comment]
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172
