### ISSUE TITLE
One UI 3 On FloydQ V6.0

### ISSUE THREAD

**Issue by Jakjjeong** [ananjaser1211/FloydQ_Reports#248]
Hello? I have a question about FloydQ V6.0 you are developing.
Does the FloydQ V6.0 you create mount One UI 3.0?

**Comment by reaitten** [comment]
It is not, it is only one ui 2.5. Please close this since this isn't a bug report.

**Comment by SkyrilHD** [comment]
As reaitten said, it's OneUI 2.5. FloydQ like how in its name says "Q" is only an OneUI 2.X Port. And there are no plans releasing OneUI 3 for 8890.
This "issue" is invalid.
