### ISSUE TITLE
[BUG] can't send rcs messages after failing one time to send rcs message (chat message)

### ISSUE THREAD

**Issue by Mocar2D** [ananjaser1211/FloydQ_Reports#249]
**To Reproduce**
1. Go to messages
2. Make a rcs messages fail
3. click ok to send it as text message (sms)
4. Can't send rcs messages
5. enabling Send as a chat messages after clicking 3 dots doesn't work
6. Still sends as text messages

**Expected behavior**
It should send an rcs message other time and the Send as a chat messages switch should work and change its state to on

**evidence**

https://user-images.githubusercontent.com/69865499/106869690-85dcc180-66d0-11eb-9a38-12a99795e67b.mp4

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F

**Additional context**
- error log [log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5924169/log_e.log) 
- resetting settings did not help

- re-flashing did not help with keeping my current files
- deleting cache and data of messages app did not help
- deleting contact and messaging it did not help still sending text messages to this number
- can send rcs messages to other numbers
- the number I was sending it supports rcs (it is glaxy s7 flashed with floydq)

**Comment by ananjaser1211** [comment]
Does your network support RCS ? rom support is not enough, you need to have RCS on the sender and receiver mobile device and network

i have not tested RCS personally, as its not rolled out in my country yet, ive only heard from testers about it. so i cant confirm if it works or not

**Comment by Mocar2D** [comment]
Hey there! Yes my network happily supports rcs, and about, and I selected during installation to force support of the rcs, and about that weird issue somehow rcs for this specific number enabled itself, but as you could see the send messages as chat switch did not work

**Comment by ananjaser1211** [comment]
i see, ill ask my testers to check it out again as i have no clue about RCS

**Comment by acharjyanisankh** [comment]
Possibly Universal profile portability issue with Your carrier even though it supports RCD

**Comment by Mocar2D** [comment]
hey @acharjyanisankh my carrier is play and I live in poland, and mcc code is 260-06 anyway I wanna post an update on this issue after using the phone normally for maybe 2 days the rcs switch fixed itself, I don't know how exactly it fixed itself, but yeah it now works again, I haven't tested the switch after failing at sending it as rcs message, and yes the other phone that I tried messaging using chat (rcs) was another samsung s7 with floydQ and turned on rcs, anyway I found another interesting issue (might just be my own phone) but after taking a photo on messages app it takes loong amount of time to attach it to the message.
