### ISSUE TITLE
[Feature] Manual CSC Adding: Colombia CSC (COO) 

### ISSUE THREAD

**Issue by brandon0606** [ananjaser1211/FloydQ_Reports#251]
[Feature] Request to add Colombia CSC (COO) 

Describe the feature
Request to add CSC of Colombia (COO).

Smartphone (please complete this feature following information part if you want device spesific):

Device: Galaxy S7 Edge
Model: G935FD
Origin of Feature
This country was in floyd v3, can you upload it again for the next version? 
I leave you the link in mega of COO in floyd_v3 in case you can do it. Happy day and excellent rom!

Q COO OMC/ODM package Floyd_v3: https://mega.nz/file/TRc2ABwJ#c5sPsbRrRG9Gy8EM9-g70uUutz2QoKsSl35OKKOex1g

**Comment by SypeR54** [comment]
Thanks for your feedback. In the next release of Floyd V6, Colombia CSC (COO) will be there also. Until the new release, you can install COO CSC by replacing files manually.

Have a nice day. 😊
