### ISSUE TITLE
[FIXED - Non relative to ROM] Youtube / Vanced history is not working properly 

### ISSUE THREAD

**Issue by indycool** [ananjaser1211/FloydQ_Reports#252]
Hi guys !
Thanks again for your amazing work, everything is working smooth with this ROM, except this little bug, found as well by M2EO6W and frostedpichunut page 76 of the [ROM][10.0][OneUI 2.5][G930X/G935X/N930X/N935X]FloydQ V5.0 thread.
 
**Describe the bug**
When using youtube or Vanced application, the history of video is not saved by google. If you quit the app and come back, you have to start the video from the beggining. History on another device is working fine and you can see it on the app. 
Reinstall the app didnt fix, and settings on Google account is fine (saving history is on). Search history is working fine tho. Using a new google account is not working either.

**To Reproduce**
1. Open Youtube app
2. Click on any video, watch for few seconds
3. Go to history, or library 
4.The video you just seen is not visible. 

**Expected behavior**
It is expected to see all the video you watched on the phone in this library / history. 

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7]
 - Model: [G930F]

**Additional context**
Could be a privacy settings, or Android 10 settings, but didnt found anything relevant. Is it working for the rest of the users ? 
Thanks for support !

**Comment by ananjaser1211** [comment]
I have this issue only with the Vanced youtube app, when i dont setup GCM from microg properly, the normal youtube app is working fine on my S7

**Comment by SypeR54** [comment]
It's latest Vanced's issue, not releated with the ROM. Older versions of Vanced works fine and saves history when its installed via Rootless method.

PS: I'm probably using Vanced's version 15.33.34 or 15.05.54. I know, its really old but if it's work, don't touch it. 😁

**Comment by indycool** [comment]
Thanks both of you for your quick answers ! 

I just tried with unroot installation with both 15.33.34 and 15.05.54, after configure GCM from microG, v0.2.16..204713 the latest one on Vanced Manager ( any settings recommandation except the one given by Vanced ? ) but still no history for now :( 

I will also try with previous version of youtube app as it should work normally

**Comment by ananjaser1211** [comment]
glad to hear
