### ISSUE TITLE
[BUG] The order of buttons in quick panel resets to initial state after each reboot.

### ISSUE THREAD

**Issue by BrainNull** [ananjaser1211/FloydQ_Reports#254]
**Describe the bug**
The order of buttons in quick panel resets to initial state after each reboot.

**To Reproduce**
1. Go to 'Quick panel> Button order'
2. Reorder some buttons
3. Click to 'Done'.
4. Reboot
5. See initial buttons order

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930FD]

**Comment by SkyrilHD** [comment]
Basically what you are describing is #113 . Could you dirty flash without selecting Extra CSC features?

**Comment by BrainNull** [comment]
> Basically what you are describing is #113 . Could you dirty flash without selecting Extra CSC features?

Oh, really. I was looking among just open issues.
