### ISSUE TITLE
[BUG] custom DNS doesn't affect connection

### ISSUE THREAD

**Issue by jowafieuzu** [ananjaser1211/FloydQ_Reports#255]
**Describe the bug**
custom DNS doesn't affect connection

**To Reproduce**
1. Go to Connection>Wifi>Setting current wifi>Advanced>IP setting
2. Change DHCP to Static, input Google DNS or Cloudflare DNS and save
3. Browser some website's URL that was blocked in your country
4. Still cannot view, custom DNS did not have the effect of changing

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model: G935F
- Version: FloydQ V6

**Comment by Kique808** [comment]
@jowafieuzu DNS has nothing to do with the issue. No matter if you change the name resolver server, if the webpage is blocked, your ISP will still prevent it from reaching you.

What you're actually looking for to unlock those webpage is a VPN app, not a DNS changer

**Comment by jowafieuzu** [comment]
@Kique808  I know you mean.
There's some site that was block by only DNS on my country.
I CAN see when changing only DNS on PC (hasn't used VPN), but cannot see when changing only DNS on phone
This's not ISP side, it's DNS issue on the rom

**Comment by ananjaser1211** [comment]
DNS resolver is working just fine here. same results if i change DNS on my computer

![photo_2021-04-05_13-04-39](https://user-images.githubusercontent.com/25624482/113557812-a7462500-960f-11eb-8e25-8bb661374ec1.jpg)
![photo_2021-04-05_13-04-27](https://user-images.githubusercontent.com/25624482/113557815-a7debb80-960f-11eb-8114-e641cc0a50b5.jpg)
![photo_2021-04-05_13-04-33](https://user-images.githubusercontent.com/25624482/113557817-a8775200-960f-11eb-8349-9843ac9f0c47.jpg)
