### ISSUE TITLE
[BUG]Aplicativo de banco nao abre 

### ISSUE THREAD

**Issue by Xeiclas** [ananjaser1211/FloydQ_Reports#256]
good afternoon guys, i have a problem with my floydq my cell phone and a sansung galaxy s7 edge and it simply does not open any bank application (NONE) and the bank that I use only works by application please fix this in version 7.0

**Comment by ananjaser1211** [comment]
This is not something "i" can fix, bank apps detect root, if magisk hide is not hiding your app, i cant do anything about it. this is the current state of android.
