### ISSUE TITLE
[BUG] Wrong camera model in EXIF tags

### ISSUE THREAD

**Issue by endolith** [ananjaser1211/FloydQ_Reports#257]
**Describe the bug**
I just realized the EXIF data of photos is tagged as SM-G965F, even though it's actually SM-G930F hardware.  The camera model needs to be correct in the EXIF tags, so it can work with photogrammetry software, etc. that gets the physical properties of the camera from a database of model numbers.

**To Reproduce**
1. Take a photo
2. Look at EXIF data

**Expected behavior**
It should say SM-G930F

**Screenshots**
![image](https://user-images.githubusercontent.com/58611/113795524-1eb4ab00-971b-11eb-8ae1-659971e30c71.png)

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
This cant be fixed, as changing the model number to G93X in props would result in other issues in the ROM (not all apps will work, missing features etc)

so i cant add such change in the ROM, you can change the prop yourself by editing /system/system/vendor/build.prop and change G965F > G930F

**Comment by endolith** [comment]
It doesn't need to be changed in the system, just in the EXIF tags

**Comment by ananjaser1211** [comment]
@endolith the EXIF generator takes the value from build.prop. which we use G965F. hence why it writes that in the image details. i dont know if there is an easy way to spoof that, i will check, but if not it probbaly will stay like that

**Comment by mathy007** [comment]
@ananjaser1211 @MKUltraBlack

**Comment by SypeR54** [comment]
> @endolith the EXIF generator takes the value from build.prop. which we use G965F. hence why it writes that in the image details. i dont know if there is an easy way to spoof that, i will check, but if not it probbaly will stay like that

https://developer.android.com/reference/android/media/ExifInterface

It was a long time but maybe we can decompile Samsung Camera and patch the function?

https://developer.android.com/reference/android/media/ExifInterface

**Comment by SypeR54** [comment]
Okay, i found where we can spoof the model number. Samsung Camera saves EXIF datas as an array to IMG file.

`SamCamera_11.0.15.73_minAPI30\smali_classes2\com\sec\android\app\camera\cropper\util\ExifUtil.smali`
This file is saving EXIF data to the IMG file. If we can manipulate it via pulling it from a new build.prop string, it should save "Captured from SM-G930F / G935F / N930F / N935F" etc.

![image](https://user-images.githubusercontent.com/12627005/129577719-ab202c47-c480-48b1-9cb7-b6bb156e8065.png)

**Comment by endolith** [comment]
I'm not using Samsung Camera, I'm using OpenCamera :/  (Samsung Camera has too much sharpening)

**Comment by SypeR54** [comment]
@endolith Then probably we cant do anything about it. Sorry man

**Comment by Cvolton** [comment]
In OpenCamera the respective functions are in net.sourceforge.opencamera.ImageSaver

notably line 2074
`String exif_model = exif.getAttribute(ExifInterface.TAG_MODEL);`
and line 2235
`exif_new.setAttribute(ExifInterface.TAG_MODEL, exif_model);`
Since OpenCamera already modifies the EXIF data, modifying line 2074 to something like
`String exif_model = "SM-G930F";`
should be good enough

**Comment by V3rB0se** [comment]
Why not just modify exif data ?
