### ISSUE TITLE
[Feature] Iris on Galaxy Note 7/FE

### ISSUE THREAD

**Issue by sht2017** [ananjaser1211/FloydQ_Reports#258]
**Describe the feature**
Iris on Galaxy Note 7/FE

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings-Biometrics and security-Irises'
2. Click on 'Register irises'
3. The irises register will be crashed

**Expected behaviour**
The irises would be registered for unlocking the phone.

**Screenshots**
NO SCREENSHOTS

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 7/FE
 - Model: SM-N930*(With Exynos)/SM-N935*

**Origin of Feature**
- Official ROM

**Comment by ananjaser1211** [comment]
IRIS is enabled now with V7.0, it works decently but sometimes it might cause a reboot, a workaround to test is disabling "screen on iris recognition"

another issue will be opened for instability based on reports
