### ISSUE TITLE
[Feature] Add cifs to kernel

### ISSUE THREAD

**Issue by Senjar** [ananjaser1211/FloydQ_Reports#260]
**Describe the feature**
Add cifs so we can mount cifs/samba volumes as a directories.

**Smartphone**
 - Device: Galaxy S7E

**Comment by ananjaser1211** [comment]
will look into it

**Comment by ananjaser1211** [comment]
CIFS has been enabled in the kernel and will be in V7.0, idk how to test it with SMB though.
