### ISSUE TITLE
[Feature] Lightning Navigation Bars 

### ISSUE THREAD

**Issue by bugger23** [ananjaser1211/FloydQ_Reports#261]
I don't know if you can set this in the settings or not, because i didn't find anything on the internet. But if i tap on the Navigation Bars, they don't light up. Is there a fix possible?

SM-G930F

**Comment by ananjaser1211** [comment]
@bugger23 On screen navigation bar ? Or hardware buttons (back, recents)

On screen navigation bar does not "light" up

**Comment by bugger23** [comment]
I mean the hardware buttons.

**Comment by ananjaser1211** [comment]
@bugger23 The hardware buttons light up normally. If you have enabled power saving they disabled

**Comment by bugger23** [comment]
Oh. My bad. I'm Sorry.

**Comment by ananjaser1211** [comment]
No problem mate
