### ISSUE TITLE
 [BUG] Having Issues on S7 Edge Microphone

### ISSUE THREAD

**Issue by justin369369** [ananjaser1211/FloydQ_Reports#263]
I have issue on my s7 edge mic.
Some times not working

 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G965F]

**Comment by justin369369** [comment]
When i restart my phone then ok.

Some time i connected net in pc. That time not working my mic

**Comment by justin369369** [comment]
When i restart my phone then ok.

Some time i connected net in pc. That time not working my mic

**Comment by SkyrilHD** [comment]
Gather logs... Simply telling the bug doesn't help

Follow this guide [Download LoggingKit](https://github.com/ananjaser1211/FloydQ_Reports#how-to-gather-logs-with-loggingkit) and [How to gather logs](https://github.com/ananjaser1211/FloydQ_Reports#with-booted-system---intended-for-crashes-fcs-and-other-system-logs)

**Comment by aorvpfrhfem** [comment]
For me, it's okay to turn off the volte(HD voice).
