### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tristan1972** [ananjaser1211/FloydQ_Reports#265]
**Describe the bug**
I have an Sm-N920T galaxy note 5 with Floyd v5.1 and the rotation does not work at all (Even auto-rotate is on)

If you know of a fix, contact me at 168798@student.vansd.org.

**Comment by ananjaser1211** [comment]
This is FloydRom discussion for the exy8890 only.

**Comment by Tristan1972** [comment]
Sorry, This is the wrong discussion.
On Fri, Jun 4, 2021 at 3:38 AM AnanJaser ***@***.******@***.***> wrote:
This is FloydRom discussion for the exy8890 only.
