### ISSUE TITLE
[BUG] Volume change

### ISSUE THREAD

**Issue by Skyterix1991** [ananjaser1211/FloydQ_Reports#268]
**Describe the bug**
This bug was around for a long time across FloydQ versions and I encountered it dozen times. When I was listening to music after a while volume buttons started changing the wrong volume type. The notification sound volume if I remember correctly instead of Bluetooth headphones volume. After it happens there is no way to get buttons to work on Bluetooth volume other than a restart.

All tho in V6 it happened to me once. On older versions it was actually once in two weeks I would guess. Not sure if that is related or I just stopped having this many issues with it.

**To Reproduce**
Not sure, it appears sometimes when listening to music and changing volume with buttons. 

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
this discussion moved to #269
