### ISSUE TITLE
[BUG] Dock icon on home screen Problem

### ISSUE THREAD

**Issue by homelesscatty** [ananjaser1211/FloydQ_Reports#270]
** Dock icon on home screen Problem **
After Install Rom v6.0 for a while now I got the dock icon Problem below the normal position. I tried to fix by clear data of One UI Home from system app in setting nothing change. Clear dalvik and cache nothing. Change screen revolution nothing. Change resolution and density nothing.

**Screenshots**

 - Device: Galaxy Note FE
- Model: SM-N935F

**Comment by homelesscatty** [comment]
![Screenshot_20210613-101832_One UI Home](https://user-images.githubusercontent.com/85815454/121794677-8d8b1480-cc34-11eb-9e78-c8a8e1c01ed5.jpg)

**Comment by ananjaser1211** [comment]
No such issue here, this seems theme related, or some overlay.
