### ISSUE TITLE
[BUG] Sound randomly plays several times per hour. No notification associated.

### ISSUE THREAD

**Issue by Elaws** [ananjaser1211/FloydQ_Reports#271]
**Describe the bug**[
Following sound](https://www58.zippyshare.com/v/7nOaUjB1/file.html) randomly plays several times per hour. No notification or app seems associated to this sound. It stops when I swipe down from the top of the screen.

**To Reproduce**
Simple clean flash of FloydQ v6.0. 

Perheaps completely unrelated, but I must add that after clean flash, I did a dirty flash (dalvik + cache) just to remove Good Lock (uninstall was required by Galaxy Store in order to install latest version), and also to change boot animation to Samsung Black (I chose Samsung White by mistake during first install).

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 edge
 - Model: G935F

**Comment by SkyrilHD** [comment]
I suggest uninstalling recently installed apps. Also, maybe GoodLock's plugin called "Nice Catch" could say which app does this sound. In addition, you could try booting to Safe Mode and see if the issue still persists. But it's completely unrelated to the ROM.

**Comment by Elaws** [comment]
Thanks for sharing your thoughts and "Nice Catch" tip @SkyrilHD !

Did a clean flash again, installed apps one by one instead of using Smart Switch restore. So far so good, will update if random sound happens again.
