### ISSUE TITLE
OneUI 3

### ISSUE THREAD

**Issue by V3rB0se** [ananjaser1211/FloydQ_Reports#280]
Any Hope for One UI 3? LOVE THIS ROM ❤️ 

**Smartphone**
 - Device: [e.g. Galaxy S7 Flat]
 - Model: [e.g. G930S]

**Comment by ananjaser1211** [comment]
I am focusing on 2.5 for the time being, 3 is a bit too laggy for our chip

**Comment by V3rB0se** [comment]
Glad to know that you're still focusing on 2.5 thanks its a great rom. i noticed my sensor doesn't work sometime and i have to reboot my device to get them to work. should i post my logs here?

**Comment by ananjaser1211** [comment]
@V3rB0se Do open a new issue with as much information / logs as possible, and if you can be specific about which sensors work (once they break use a software like sensor multitool to test each oen of them)

**Comment by V3rB0se** [comment]
thanks I will do just that

**Comment by V3rB0se** [comment]
A question i wanted to ask is it possible to port [Cronos_8890](https://github.com/ananjaser1211/Cronos_8890) kernel for nethunter ?

**Comment by ananjaser1211** [comment]
@V3rB0se i would prefer if you use the nethunter kernel from xda (called wirus mod i belive), it is based on morokernel and has pretty much everything needed. 
corons currently is trash and needs a full rework, so wont be implementing anything anytime soon

**Comment by V3rB0se** [comment]
That's pretty much it, thanks

**Comment by V3rB0se** [comment]
Hi, again sorry if i'm being annoying asking too many question. is wirusmod kernel compatible with this rom?
