### ISSUE TITLE
[BUG] Random Freezes (Possible OOM)

### ISSUE THREAD

**Issue by V3rB0se** [ananjaser1211/FloydQ_Reports#282]
**Description**
Random Freezes wallpaper turns black with unresponsive power button 
it only occurs sometimes.

**Screenshot**
![Home Screen ((Screenshot))](https://user-images.githubusercontent.com/40388232/145831932-e045c144-5559-4a85-9cf7-0559c21f1352.jpg)

i know it won't make any difference in finding the bug just wanted to show the homescreen 

**Smartphone**
 - Device: [Galaxy S7 Flat]
 - Model: [G930S]

**Additional Logs**
- 
[Logs](https://github.com/ananjaser1211/FloydQ_Reports/files/7704551/log_All.log)

**Comment by V3rB0se** [comment]
[Present](https://github.com/ananjaser1211/FloydQ_Reports/issues/262 )

**Comment by ananjaser1211** [comment]
Thanks for the LOG ! possible cause seems to be OOM killer, (out of memory) similar to what ive faced in the galaxy S8 under Q.

This is different from what ive thought earlier (it being kernel related)

Hopefully will be able to take a look at it once my S7 board arrives.

**Comment by V3rB0se** [comment]
Thanks, i just found your s7 board died.  i appreciate you're still working on it. i recently flashed moro kernel 8.8 or something i don't remember I'll let you know if it's a kernel related issue.

**Comment by ananjaser1211** [comment]
RAM configs were re-tuned in V7.0, if the issue persists or another random freeze occurred, please report again.
