### ISSUE TITLE
[Feature] One UI 4 ?

### ISSUE THREAD

**Issue by Anton852** [ananjaser1211/FloydQ_Reports#283]
Any plans on one ui 4?

Why one ui 4? 
1. Very customizable
2. App privacy (like your awared if an app is using your phone's camera and microphone.)
3. Very future proof

I hope you do cuz I really love your floyd q rom so much <3 thank youuuu

 - Device: [ Galaxy S7 Edge ]
 - Model: [ G965FD]

**Comment by mathy007** [comment]
@Anton852 Our hardware is not even capable to run OneUI 3 you're asking for OneUI 4? If it'll be possible you'll know so stop asking.
