### ISSUE TITLE
Cant create work profile

### ISSUE THREAD

**Issue by conducked** [ananjaser1211/FloydQ_Reports#285]
Hey I keep getting a error saying Can't create work profile, the security policy prevents the creation of a work profile because a custom rom has been installed on this device. 
I was rooted a year ago but I unrooted and put the official firmware back on

**Comment by ananjaser1211** [comment]
Stock ROM issues are not relevant to this reports page, you get that error (along side secure folder) because your knox counter is 0x1, it cant be reset once you root once, the only way to get these features back is to use a custom ROM that has them enabled by patches
