### ISSUE TITLE
[BUG]? csc dbt not working correctly 

### ISSUE THREAD

**Issue by RobertoWa** [ananjaser1211/FloydQ_Reports#290]
**Describe the bug**
csc profile "dbt" not working correctly on provider telekom. no volte support activated. message popup i should call provider to activate volte.

**Expected behavior**
support of volte/wifi call on csc "dbt" provider telekom.  on floyd v6 it is working.

**Smartphone**
 - Device: Galaxy S7
 - Model: G930F

**Additional context**
it is a clean install of v7

**Comment by RobertoWa** [comment]
fix:

i replaced the dbt config files by the v6 files and it is working as it should.

**Comment by rainer7777** [comment]
> fix:
> 
> i replaced the dbt config files by the v6 files and it is working as it should.

Hi,
can you pls explain which files and what to modify?

BR Rainer

**Comment by RobertoWa** [comment]
just replace the files inside directory /odm/etc/omc/DBT by the files of v6.

i also added the following line inside /odm/etc/omc/DBT/conf/cscfeature.xml

<CscFeature_SystemUI_ConfigDefQuickSettingItem>VoLte</CscFeature_SystemUI_ConfigDefQuickSettingItem>

**Comment by rocky-svg** [comment]
that worked, thx very much

**Comment by ananjaser1211** [comment]
CSC Has been updated in V8 , the DBT csc we tested did not report any issues so far. re-open if issue persists

**Comment by RobertoWa** [comment]
seems to work so far. thanks.

only one thing i noticed at dbt conf:

there are 2 lines of EnableVoLTEindicator in the customer.xml. 1st enables it and the following 2nd disable it again, so no volte icon appears in the statusbar.

i deleted the false line and so it is fixed.
