### ISSUE TITLE
[BUG] Muffled audio on S7 and S7 Edge

### ISSUE THREAD

**Issue by n00b69** [ananjaser1211/FloydQ_Reports#300]
**Describe the bug**
Audio is muffled when this rom is installed. The equalizer cannot fix this. The speakers aren't broken because the audio works fine on the stock rom. 
The overall volume is also not as high as on the stock rom.

**To Reproduce**
1. Have FloydQ installed
2. Listen to any kind of song

**Expected behavior**
The audio shouldn't be muffled, and the audio should be louder.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7, Galaxy S7 Edge
 - Model: G930F, G935F

**Comment by ananjaser1211** [comment]
Your speakers are fine, the audio in this project has been very problematic (look up audio in the issues page) , its a mix between using another device's audio driver + samsung's changes in soundFX, Pie had clearer audio.

**Comment by ananjaser1211** [comment]
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172

* We switched to Pie audioFX with much less pronounced "muffling"
