### ISSUE TITLE
[BUG] Roborock app stuck on the starting logo screen

### ISSUE THREAD

**Issue by ZiPouet** [ananjaser1211/FloydQ_Reports#302]
**Describe the bug**
After installing the Roborock application, it does not pass the first screen with the Roborock logo.

**To Reproduce**
1. Install the "Roborock" App on play store
2. Open the App
3. You'll see the app launching with the logo of Roborock and then nothing happens.

**Expected behavior**
I have no idea because I never had this problem with my S7 when it was on Android 6 to 8 included.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F
 - Floyd 7 with all fixes

Thanks.

**Comment by ananjaser1211** [comment]
Thank you for the report, i have not yet debugged it, but did search online, the Roborock app seems to be anti-root/custom fw and has strict root detection, you could try to bypass it with magisk hide or whatever the new method is, but for the most part it does not run once the phone is rooted/custom fw

https://www.reddit.com/r/Roborock/comments/of4dw7/rborock_rock_app_on_rooted_android/

https://www.reddit.com/r/Roborock/comments/132pi52/roborock_app_crash_on_custom_rom/

**Comment by ZiPouet** [comment]
> Thank you for the report, i have not yet debugged it, but did search online, the Roborock app seems to be anti-root/custom fw and has strict root detection, you could try to bypass it with magisk hide or whatever the new method is, but for the most part it does not run once the phone is rooted/custom fw
> 
> https://www.reddit.com/r/Roborock/comments/of4dw7/rborock_rock_app_on_rooted_android/
> 
> https://www.reddit.com/r/Roborock/comments/132pi52/roborock_app_crash_on_custom_rom/

I did hide Magisk but maybe I did it wrong :/
My banking apps and otehrs all works, that's really the only one so that surprises me.
Here is the result of the memory detector app if that can help: https://forum.xda-developers.com/attachments/screen-jpg.5976971/

**Comment by ZiPouet** [comment]
Update here:
I've uninstalled Magisk but sadly it does not change the situation. I don't know how Roborock detect the custom rom but it's clearly a problem. If you debug that App, would that work after a hotfix on your side?
Thanks for everything :)

**Comment by ZiPouet** [comment]
> Thank you for the report, i have not yet debugged it, but did search online, the Roborock app seems to be anti-root/custom fw and has strict root detection, you could try to bypass it with magisk hide or whatever the new method is, but for the most part it does not run once the phone is rooted/custom fw
> 
> https://www.reddit.com/r/Roborock/comments/of4dw7/rborock_rock_app_on_rooted_android/
> 
> https://www.reddit.com/r/Roborock/comments/132pi52/roborock_app_crash_on_custom_rom/

Update here:
I've uninstalled Magisk but sadly it does not change the situation. I don't know how Roborock detect the custom rom but it's clearly a problem. If you debug that App, would that work after a hotfix on your side?
Thanks for everything :)

**Comment by ananjaser1211** [comment]
i think something like kernelsu might help keep root while bypassing the app, but im not sure, the thing is after unrooting with magisk the device will fail CTS (since the rom is outdated, and the device fingerprint we use is no longer the most recent one)

refer to this comment https://github.com/ananjaser1211/FloydQ_Reports/issues/301#issuecomment-1676098802

if you are able to get CTS passing + not having magisk installed + the TWRP folder renamed to Recovery in /sdcard, you have a higher chance of making it work, i have not had time to get working on the S7 yet, but the fingerprint i mentioned in that comment is likely to fix CTS passing by default (with no magisk / root installed)

**Comment by ZiPouet** [comment]
Went to the kernelsu site but sadly I could not find which file to download cause the Kernel I have on my mobile after installing your rom is "3.18.140-CronosKernel-V7.0-G930X-Q-20220701". So on their they recommand sticking to the existing kernel but they rather look like something "android X", "AnyKernel3-android X", "kernel-ARCVM", kernel-WSA"... :/
https://github.com/tiann/KernelSU/releases

**Comment by ananjaser1211** [comment]
As part of the recent safetynet fixes and the introduction of KernelSU, This app no longer crashes on splash screen.

**Comment by ananjaser1211** [comment]
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172
