### ISSUE TITLE
[BUG] (ESP) Camera stops working randomly. 

### ISSUE THREAD

**Issue by 0800komma** [ananjaser1211/FloydQ_Reports#303]
La cámara deja de funcionar de forma aleatoria. La app de cámara se cierra sola, la cámara no funciona en apps con cámara. Aparentemente colapsa y deja de funcionar. La única solución es reiniciando el teléfono, aunque este problema sucede muy frecuentemente.

**Comment by ananjaser1211** [comment]
Re-test with V8 and if the issue persists, follow the guide on how to take logcats and get /data/log / data/tombstones aswell, we changed some behavior's in camera that should prevent camera server failure
