### ISSUE TITLE
[BUG] separate sounds not working

### ISSUE THREAD

**Issue by albertodurmiendo** [ananjaser1211/FloydQ_Reports#35]
**Describe the bug**
Option in settings and sound assistant separate sound or playing audio in bluetooth and mobile with different sound is not working.

**To Reproduce**
1. Set separate app  in settings 
2. Connect to bluetooth speaker
3. Play sound using the selected app
4. Play sound from different app, like youtube

**Expected behavior**
The Samsung Separate App Sound feature allows you to play music from your smartphone from one app to a Bluetooth device, such as speaker or headphones. For example, you may want to watch the movie, but you don't want interrupted by a call during the time. When it is enabled, you’ll still hear system sounds from your smartphone’s speakers, such as alarms and the ringtone to alert you of an incoming call.

**Screenshot**
![20200429_032749](https://user-images.githubusercontent.com/49085370/80861724-ed2d9700-8ca2-11ea-8a77-138172422297.jpg)
Slider highlighted is not working

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930FD

**Comment by ananjaser1211** [comment]
I have not done anything special in the new Base, but i tested the feature and it was working (i had youtube play on the bluetooth device and samsung music on the phone)

there was no issue playing both sounds even at the same time
