### ISSUE TITLE
[BUG] sometimes wifi won't connect at all

### ISSUE THREAD

**Issue by sbappii** [ananjaser1211/FloydQ_Reports#36]
[Log_2020-04-23_11-24-01.txt](https://github.com/ananjaser1211/FloydQ_8890/files/4520814/Log_2020-04-23_11-24-01.txt)
**Describe the bug**
Wifi doesn't want to connect at all. It fixes if I turn off and on wifi 

**To Reproduce**
Once this happened when wifi was on and connected at night and in morning this happened.
The other time I was out of wifi range and when I came back it was like that(after this I took logs).

**Expected behavior**
You know
**Screenshots**
Sorry next time.

**Smartphone (please complete the following information):**
 - Device: Galaxy s7 edge
 - Model: G935FD

**Additional context**

**Comment by aykuxt** [comment]
The same thing happens to me when I download something with Chrome. If the screen turns off during the download, the WiFi connection is disconnected and I have to turn the WiFi off and on again to restore the connection.

**Comment by ananjaser1211** [comment]
Currently we suspect that Bluetooth Low Energy features are causing the issue, BLE constant scanning (on our BT 4.2 device) is causing issues. disabling it 

ive attached a flashable zip with some changes to disable some background bt scanning. i cant test it here as my connection does not face any issues (its only 30mbps)

Note : this will disable navbar if you have it installed

[BLE.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4538145/BLE.zip)

**Comment by aykuxt** [comment]
Just happened to me again today. After unlocking my phone, WiFi was disconnected and I had to re-enable wifi to reconnect.

**Comment by sbappii** [comment]
The bug is fixed for me. I didn't reply earlier because I wanted to test for as it happens once in 2 days. Thank you!

**Comment by MTsCetin** [comment]
https://drive.google.com/open?id=1sA5g34At1ipFV4XB3U4yb7T3X9UdkKR6

Hi,

After flashing BLE.zip Wifi keeps disconnecting randomly, in this very log you may find lots of disconnections and reconnection attempts.

I'm on U4

Thank you!
