### ISSUE TITLE
[Enhancement] Secure Folder

### ISSUE THREAD

**Issue by rock6663** [ananjaser1211/FloydQ_Reports#44]
I know i you gonna add it on later releases i read about it on telegram but im starting this thread for other people who dont know that you are going to add that on one of rom's next releases

**Comment by ananjaser1211** [comment]
After trying on and off for the past month, This feature is not going to work on our Port.

It seems to be a combination of Q changes in how TIMA is handled, whatever was broken in pie that led it to work is no longer the case here.

Only some devices seem to be able to retain secure folder with 0x1 knox (S9 And Note 9 so far i am aware of) . But that seems to be linked to their TLC keystore, which is not something you port.

So yeah, RIP secure folder. those who want it will have to revert to Pie

**Comment by ananjaser1211** [comment]
SecureFolder has been patched, and will be avalible in V4

I came up with a better patch and hacked the issue that our keystore cant deal with.
