### ISSUE TITLE
[BUG] Slow Fast Charging

### ISSUE THREAD

**Issue by SkylakeRyzen** [ananjaser1211/FloydQ_Reports#46]
**Describe the bug**
I noticed that fast charging is too slow. Using ampere i monitored the current input MAh of my phone. I will goes like this. It will start at 2400mah and then will drop at 1365mah and will stay at that until full. Usually it should be 2400mah until 60% tried this on cronos kernel and moro.

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
I am pretty sure your battery is running too hot, similar people reported such issue except they were gaming while fast charging and using the phone hard. 

cant do much about this since all charging is handled in the kernel, which did not change significantly from pie.

**Comment by SkylakeRyzen** [comment]
Im pretty sure its not with the heat. Theres something wrong with then ROM. I did not have the issue on BD ROM

**Comment by SkylakeRyzen** [comment]
It will automatically drop on 1360 mah after a minute or so. Im also sure not a hardware problem cables and charger tried swapping cables and stuff. I can conficentally say that its in the ROM

**Comment by ananjaser1211** [comment]
> Im pretty sure its not with the heat. Theres something wrong with then ROM. I did not have the issue on BD ROM

BD rom is also not running Android Q and a much heavier skin under the hood.
measure your battery temperature while charging, we had 3 people report "charging issues" when their phones battery were running above 42C and throttling hard

there is nothing ROM sided that i can do to control charging, it is all in the kernel, which again, is identical to Pie kernel that had zero issues.

i have sustained fast charging here and the phone charges in an hour and half give or take. for the past 3 months

**Comment by SkylakeRyzen** [comment]
You will not notice the bug when you use your phone normally but if you use it while gaming then the issue will appear. Battery will not charge while gaming. I mean it is charging but percentage will go down instead of up because of too much heat or something. Thus, your battery will just drain instead of charging and it annoying.

On BD rom it is a different story. when i tried the same setup from floyd to BD rom the issue went away. My phone is perfectly charging while gaming even is too hot.

**Comment by SkylakeRyzen** [comment]
My point is i had the same setup from floyd to BD but when i tried it in BD Rom i never had the issue. So somethings might be wrong in the ROM not the kernel because i used same kernel in both ROM and gave different results.

**Comment by ananjaser1211** [comment]
I see your point, I will take another look at this, even tho i really have no clue what ROM sided could govern such thing as its only kernel related.

i have not tried fast charging and gaming, id like if possible to tell me your mAh rate while playing a certain game on BD, so we have a baseline to work with.

**Comment by shariq342** [comment]
@SkylakeRyzen are you 100% sure? Am not having this issue on my s7. Fast charging drops to 1.6A when near 80% and drop to near 0.8A when near 90%
From 0 to 80 its nears 2.3 , 2.4 A

**Comment by SkylakeRyzen** [comment]
@shariq342 you are not having issue because I assume your phone does not reach 40C and above. I posted a video about this in a different thread.

**Comment by shariq342** [comment]
@SkylakeRyzen Yup thats true. And its a normal behavior on All phones that when phone reaches 40C it drops the mA to 700 800 mA 
And if the temp rise above 41C
It will stop the charging.

**Comment by shariq342** [comment]
![Screenshot_20200507-192120_Bromite](https://user-images.githubusercontent.com/61206202/81305591-f4381900-9097-11ea-990f-631971723eeb.jpg)
