### ISSUE TITLE
[BUG] Broken Frequency Scaling

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#47]
This is most likely the cause for the additional heat this ROM produces, the phone tends to run at a higher clock under similar CPU %

Possible Culprits :
1- Improper SSRM/HRM Config
2- Power_profiles needs manual tuning
3- PowerHAL Needs revisiting

**Comment by SkylakeRyzen** [comment]
This is what im telling you. Thats why fast charging is too slow on your ROM. Even if you manual set cpu frequency it will still eat a lot of power and the phone wont charge properly

**Comment by ananjaser1211** [comment]
> This is what im telling you. Thats why fast charging is too slow on your ROM. Even if you manual set cpu frequency it will still eat a lot of power and the phone wont charge properly

I have not seen any change in the charging rate with my recent change (i am now using n7fe HQM config) my phone still charges at the same rates. however the important part is fixing the cpu scaling which will cause additional heat.

since you have the issue, could you try the fix for me. unpack this file (so you get hqm_device.xml)
copy it to system/system/etc/ through twrp file manager and chmod 0755,

let me know if rates improved. mine remained similar. 

[hqm_device.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4534685/hqm_device.zip)

**Comment by SkylakeRyzen** [comment]
Okay. Will give you the result. I just need to go back to floyd again.

**Comment by SkylakeRyzen** [comment]
![Screenshot_20200427-163738_Settings](https://user-images.githubusercontent.com/64305486/80439500-8895c500-88bb-11ea-825c-2a3a570c8c09.jpg)
Kernel. All default

![Screenshot_20200428-013540_Ampere](https://user-images.githubusercontent.com/64305486/80439518-951a1d80-88bb-11ea-8a02-bb2412318df4.jpg)
![Screenshot_20200428-013807_Ampere](https://user-images.githubusercontent.com/64305486/80439569-afec9200-88bb-11ea-9067-998075b96799.jpg)

So i noticed the issue starts to show when the phone's temp is at 40C and above and is gaming. My battery will drop its percentage and will not go up. It seems like its eating a lot of power. 

Note that i already applied your XML in this test.

![Screenshot_20200428-013959_Mobile Legends Bang Bang](https://user-images.githubusercontent.com/64305486/80439802-3dc87d00-88bc-11ea-9b99-d9edddca3cdb.jpg)

Not sure if this will help. If i have an estimated time when my battery will be full in status bar it charges normally.

![Screenshot_20200428-014036_Mobile Legends Bang Bang](https://user-images.githubusercontent.com/64305486/80439878-62245980-88bc-11ea-87ef-6c2d11f3ef60.jpg)
But if its does not say something battery percentage will just go down or will not charge as fast as normal.

**Comment by SkylakeRyzen** [comment]
In pie\bd ROM it still charges even of i hit 47C while gaming. I will try to capture a video and post it here.

**Comment by SkylakeRyzen** [comment]
https://streamable.com/kybiz3

Here is the video. Notice that it drops from 77% to 75%

**Comment by ananjaser1211** [comment]
> https://streamable.com/kybiz3
> 
> Here is the video. Notice that it drops from 77% to 75%

This is extremely confusing scenario, the phone has over 1000mah going in yet it is "discharging" .
through out the video i notice once it hit 42.3C it dropped from 3.812v to 3.675v then kicked back to 1600mah

almost as if there is an artificial limit on 42C imposed somewhere in the ROM. sadly i have no idea where to find this at the moment.

Do you have the same behaviour with MoRo Kernel ? (I am asking moro specifically because it uses oreo charging driver / battery configs compared to ts and cronos that use pie )

**Comment by SkylakeRyzen** [comment]
Yes. It is really confusing. Just let me know if you need to test something and Im willing to do it for you just to fix this bug.

**Comment by DinhVanZz** [comment]
I have the same problem, we just need to increase the maximum charging temperature and the problem will be solved but I don't know where to fix it, someone help me
