### ISSUE TITLE
[Enhancement] Update prebuilt YouTube Vanced

### ISSUE THREAD

**Issue by aykuxt** [ananjaser1211/FloydQ_Reports#49]
The apk version in aroma installer is very old. A newer version is available (15.05.54).

**Comment by SkylakeRyzen** [comment]
Then update it in magisk? I think it is not considered as bug

**Comment by ananjaser1211** [comment]
Updated vanced needs microG for login, we use this old version (that still works) and does not require microG

if you want the latest you can update it through the magisk module.

**Comment by aykuxt** [comment]
Youtube Vanced doesn't support the Magisk module anymore anyway and the latest version on their official website doesn't need MicroG if I'm not mistaken. (root-variant)

**Comment by ananjaser1211** [comment]
> Youtube Vanced doesn't support the Magisk module anymore anyway and the latest version on their official website doesn't need MicroG if I'm not mistaken. (root-variant)

oh ok, i am not very upto-date on vanced, all i remember is any other version that i tried just failed.

ill ask around and see which root version we can preload

**Comment by Cvolton** [comment]
the issue with Vanced is that newer versions require apk signature verification to be disabled, since Google uses APK signature scheme v3 now

**Comment by shariq342** [comment]
Well indeed. New YT vanced needs disabled google signature check

**Comment by ananjaser1211** [comment]
as per @shariq342 . ill keep it using the old version until it stops working, when that happens we will just drop vanced from the AROMA. 

disabling signature verification causes with other apps, snapchat and facebook to be excat
