### ISSUE TITLE
[BUG] No Vulkan api support

### ISSUE THREAD

**Issue by alexandrexild** [ananjaser1211/FloydQ_Reports#54]
there is no vulkan api in the rom, reason for not playing games that this api has.

**Comment by ananjaser1211** [comment]
Can confirm this BUG, however could you please suggest me games that use vulkan. as last time i tried to fix it i had nothing to test it on

**Comment by alexandrexild** [comment]
in the game ark mobile, in the start menu it says that the device has
no vulkan api, and in the emulator (ppsspp) going in settings,
graphical api, there is also no vulkan only OpenGL. I hope I was of
help


Em seg, 27 de abr de 2020 04:35, AnanJaser <notifications@github.com>
escreveu:

**Comment by ananjaser1211** [comment]
Thank you that is perfect.

**Comment by alexandrexild** [comment]
Hi how are you?
I would like to know when the update for the vulkan correction will come out?



Em seg, 27 de abr de 2020 08:10, AnanJaser <notifications@github.com>
escreveu:

**Comment by ananjaser1211** [comment]
@alexandrexild When i figure out what is wrong and fix it. right now vulkan is not on my priority list. i have other bugs to look into first.
