### ISSUE TITLE
[Feature] Rounded corner option in Aroma

### ISSUE THREAD

**Issue by Switchof** [ananjaser1211/FloydQ_Reports#56]
**Describe**
First of all thank you Anan for the great rom.This is just a req since main function of the rom working as it should be.I will be much appreciate if possible to add rounded corner as a choice in aroma or separate flashable zip for people who needed like me :) It also will make floyd more beautiful since a lot of rounded corners in ui.
Understood that there is plenty of apps that can do this but i prefer the less resource method (battery saving purpose)

**What i do**
I tried edit floating_feature.xml line framework_config_rounded_corner_radius and ended in bootloop.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7E
 - Model: G935F

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
The values to change are 

`SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_ROUNDED_CORNER_RADIUS` from 0 to 26

and 

`SEC_FLOATING_FEATURE_SYSTEMUI_CONFIG_CORNER_ROUND` from 0 to 5.0

When editing system files in Q, it is better to copy the file to your /sdcard (vendor/etc/floating_feature is the file to edit ofc)

do the edits then copy it back to vendor/etc/floating and set perm 0644 then reboot, if it bootlooped open twrp and mount system, through twrp file manager go to `system/system/vendor/etc/floating_feature.xml` press on it and click chmod 0755

**Comment by Switchof** [comment]
> The values to change are
> 
> `SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_ROUNDED_CORNER_RADIUS` from 0 to 26
> 
> and
> 
> `SEC_FLOATING_FEATURE_SYSTEMUI_CONFIG_CORNER_ROUND` from 0 to 5.0
> 
> When editing system files in Q, it is better to copy the file to your /sdcard (vendor/etc/floating_feature is the file to edit ofc)
> 
> do the edits then copy it back to vendor/etc/floating and set perm 0644 then reboot, if it bootlooped open twrp and mount system, through twrp file manager go to `system/system/vendor/etc/floating_feature.xml` press on it and click chmod 0755

I did copy the floating_feature.xml file using twrp from system/system/vendor/etc and edit it using notepad++ in computer then replace it again to the folder using twrp and set permission 0644.I didn't use any file explorer since the device is not rooted.

The value i changed was 
>
`SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_ROUNDED_CORNER_RADIUS` from 0 to 26
>
`SEC_FLOATING_FEATURE_SYSTEMUI_CONFIG_CORNER_ROUND` (Never changed this value but the default was 1.5 and not 0)

Does the permission is wrong or could be anythg else?Thank you for replying :)

**Comment by shariq342** [comment]
Trying Giving permission chmod 0755.

**Comment by Switchof** [comment]
> Trying Giving permission chmod 0755.

It's weird now..I did clean flash rom again but this time both data and cache is f2fs.Nw even with chmod 0775/0664 floating_feature.xml the rom is booting but there is no any visible changes.I did tried a few times with different values in both lines :|
