### ISSUE TITLE
[BUG] Make Audio Great Again!

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#59]
I will combine all the previously mentioned Audio issues in here. since they are all related to the same thing in the end. 

Issues initially reported by : 
@kaos126 @Skyterix1991 @B3rthelot @shariq342

BUG #15 `audio compared to an old Rom is higher but is heard with less bass`
BUG #28 `The audio behaves in some situations like it doesn't respond to volume change. Mainly notification sounds.`
BUG #33 `Phone goes silent,even if it is on sound`
BUG #26 `No Audio below certain point`

After a full day of tuning and fixing, Me and the testers have finally found a proper way to handle audio, as per reports the BASS is good again (BUG #15 ), the sound is no longer Flat. it was broken due to a certain audio processing lib being busted

after fixing that, we tuned the output to reduce it a bit. What samsung has done in Q baffles me, They reduced actual Gain through mixers, but increased the sound using soundAlive. i dont understand the purpose, but this forces us to also reduce our GAIN to match "modern Q devices"

The patch attached also reduces the horrid notification / charging / ringtone sounds, and you will be able to increase/decrease their sounds by changing the system sounds (BUG #28 )

Finally, After fixing soundAlive, i have plugged in and out my device almost 50 times trying to recreate the bug where sound just gets disabled, and so far it has not happened, however i need more people to use the new sound setup to let me know if that bug is fully gone or not.

Please let me know how it goes. Thanks

**Forgot to credit the two testers who spent hours on this with me. how stupid. Big thanks to @MissACCA and @IbrahiM10 for non stop testing and investigation on this issue for the past week.**

[FloydAudio69.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4541773/FloydAudio69.zip)

**Comment by matinzd** [comment]
That was great thanks for the fix. I will inform you if I faced any issues :XD

**Comment by jame25** [comment]
Viber msg notification audio now working reliably since flashing file.

**Comment by JeffS2Duda** [comment]
I will flash the file now and report if I see any more problems with the audio.

**Comment by JeffS2Duda** [comment]
I was not using my cell phone for a while, 1 hour or so, when I went to use it now the sound was bad.

**Comment by Vivigens** [comment]
I installed the fix without a result. The Loudspeaker still sound horrible (no bass!). Maybe because I`m using a a personalized sound setup?! If I listen over the BT-In-Ears the sound is perfect.

**Comment by ananjaser1211** [comment]
> I installed the fix without a result. The Loudspeaker still sound horrible (no bass!). Maybe because I`m using a a personalized sound setup?! If I listen over the BT-In-Ears the sound is perfect.

Based on the 20 testers that used this, they all claim the sound matched Pie (the bug was the sound was too flat, and lacked all bass and vol sliders lacked control over some sounds) after the fix it was at the same level of pie, which is my benchmark

if you are using custom 3rd party tools to control the sound (v4a for example) it will override what the fix will do anyway. you can always increase bass through 3rd party. i dont use the speaker that often except when watching youtube, and it "sounds" find so im not sure what more tuning can be done

> I was not using my cell phone for a while, 1 hour or so, when I went to use it now the sound was bad.

Can you elaborate ?

**Comment by Vivigens** [comment]
> i dont use the speaker that often except when watching youtube, and it "sounds" find so im not sure what more tuning can be done
Same here! I just wanted to share it for completeness. The Headphonesound is perfect and the Vol.-Sliders working correct...

**Comment by JeffS2Duda** [comment]
I'm having problems with the audio, but not very often.  Sometimes it happens that Audio stops working when I have been using the cell phone for a long time and then I stop using it for a little while longer, then when I pick it up, the audio is no longer working.
It also happened that Audio stopped after I finished watching a video on Facebook, so the video ended. I went on Whatsapp to listen to an audio that had been sent to me and the sound was not coming out.

**Comment by jamal4sabr** [comment]
After flashing the fix, the issue still occurs but not too often, like yesterday i rebooted twice. Thank annan

**Comment by ananjaser1211** [comment]
I have improved the fix further in the next release, still tracking why some loose audio tho

**Comment by jamal4sabr** [comment]
Thanks anan, may Allah accept all your acts of worship in this ramadan.

**Comment by MTsCetin** [comment]
the phone randomly goes completely mute even I've flashed FloydAudio69.zip patch.

https://drive.google.com/open?id=1RvPltTMFySlC2t74R8dHzBKdtH6KIa4g
https://drive.google.com/open?id=1EaRfX2x_Nl_c_VDzx4twdIgNgYFE_6W2

**Comment by ananjaser1211** [comment]
Discussion for "Muting" Bug has been moved to #103 as it is still an Active issue
