### ISSUE TITLE
[BUG] One handed mode not working

### ISSUE THREAD

**Issue by aladie** [ananjaser1211/FloydQ_Reports#62]
**Describe the bug**
If you try to enable the one handed mode in settings, it simply doesn't wanna work. So basically if you choose the option to enable this feature with a double tap on the home button it just takes you to the home screen. (So this is just a minor bug so please focus on the important stuff first ;-))

**To Reproduce**
1. Go to settings 
2. Click on extended functions
3. Scroll down to the one handed mode
4. Enable it and see that it's not working at all

**Expected behavior**
Working one handed mode

**Screenshots**
![Screenshot_20200428-112445_Settings](https://user-images.githubusercontent.com/47330742/80471109-3b5d3600-8943-11ea-9c28-c64b8a91b02c.jpg)
![Screenshot_20200428-112452_Settings](https://user-images.githubusercontent.com/47330742/80471123-4021ea00-8943-11ea-9ae1-2fb4c91b4e7d.jpg)

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
After some testing, this issue seems to "work as expected" as in, it only lets you use that option when it sees a navibar. not with physical buttons.

This is more or less a limitation of the S9 base
