### ISSUE TITLE
Audio quality IG stories

### ISSUE THREAD

**Issue by kaos126** [ananjaser1211/FloydQ_Reports#76]
Unfortunately the audio quality even in the stories is pretty bad. If i upload a story with a music this after the upload sounds terribile. I already have installed the audio fix but i don't why I don't see any difference from before. So the audio As i have already reported in the bug #15  at least for me It hasn't changed.

**Comment by shariq342** [comment]
It's fine here.

**Comment by ananjaser1211** [comment]
So, any more info on this bug ? and a video to explain "bad sound quality" as its not really something i can just tell.

Audio quality with the recent fix sounds just fine. so im not sure. please provide more info
