### ISSUE TITLE
Imei number 'null'/UNKNOWN?

### ISSUE THREAD

**Issue by xsalarie** [ananjaser1211/FloydQ_Reports#78]
Hi there,

I installed your rom yesterday as said in the installation guide, I was running a custom rom of oneui 1.0 previous before your rom. Everything worked awesome for the exeption of the bugs labeled here or in f.a.q. so when I tried a sim card in this phone it didn't register to the network (vodafone) and when I went looking in device infinity I saw that I do not have an imei number on this device, so tried to call a weird code on my phone to see if field test mode was enabled but I'f I dial the code it freezes the dial pad. Do you have any ideas on how to fix this or did I miss something in the install guide

With mutch love for the rom,

Xander

**Comment by shariq342** [comment]
Dirty Flash the rom and choose your csc manually.
