### ISSUE TITLE
[BUG]  video stabilization and audio

### ISSUE THREAD

**Issue by kaos126** [ananjaser1211/FloydQ_Reports#8]
The video stabilization doesn't work, and the audio is worst than oreo rom.

**Comment by ananjaser1211** [comment]
EIS has been disabled (Video stabilization option)  to prevent video tearing and other similar issues,

OIS stabilization works by default and does achieves he same quality anyway.

Regarding Audio, i cant confirm this claim, open it in a separate issue with proper reporting. it "sounds" fine here

**Comment by gusttavh** [comment]
No ? 😔😔😔
