### ISSUE TITLE
[BUG] mobile hotspot not working unless connected to a wifi network 

### ISSUE THREAD

**Issue by dtriguero** [ananjaser1211/FloydQ_Reports#80]
**Describe the bug**
Mobile hotspot turns on and other devices can connect but other devices can not use internet via mobile data but if phone is connected to a wifi network. Other device can use internet with mobile hotspot but only via wifi sharing. Also wifi sharing option is greyed out and unable to turn off. So unable to see if is the reason.

**To Reproduce**
1.Turn on mobilehotspot
2. connect to it with another device
3. Try using internet on other device
4. Disconnect device 
5. Turn on wifi and connect
6. Reconnect other device
7. Try using internet on other device

**Expected behavior**
 Creat hotspot to use internet on another other device Using mobile data 
**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [ Galaxy S7]
 - Model: [ G930F]

**Additional context**
Wasn't sure where to get or what logs would be of help. Let me know and will try and get them.

- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
I dont have a simcard in my phone right now to test, but i remember we were able to turn off wifi sharing and then share data with mobile data. (ive tested it for couple mins only as this was a bug before)

Also be sure you are using Cronos kernel, as other kernels might not have hotspot support. i dont remmeber if all of them added it

**Comment by dtriguero** [comment]
I managed to get wifi sharing turned of. Having auto share hotspot turned on is what was stopping me from being able to toggle wifi sharing on and off.

Unfortunately devices connected to hotspot still cannot use internet with out me using as wifi sharing. I am using your chronos 3.5 kernel.

**Comment by dtriguero** [comment]
@ananjaser1211 I managed to get wifi sharing turned of. Having auto share hotspot turned on is what was stopping me from being able to toggle wifi sharing on and off.

Unfortunately devices connected to hotspot still cannot use internet with out me using as wifi sharing. I am using your chronos 3.5 kernel. I've never had issues using hotspot with mobile data in the past on other older roms so I don't think it would have anything to do with the sim card or mobile carrier. Will keep trying things to see if I can some how manage to get it working using mobile data.

**Comment by ananjaser1211** [comment]
> @ananjaser1211 I managed to get wifi sharing turned of. Having auto share hotspot turned on is what was stopping me from being able to toggle wifi sharing on and off.
> 
> Unfortunately devices connected to hotspot still cannot use internet with out me using as wifi sharing. I am using your chronos 3.5 kernel. I've never had issues using hotspot with mobile data in the past on other older roms so I don't think it would have anything to do with the sim card or mobile carrier. Will keep trying things to see if I can some how manage to get it working using mobile data.

Just tested , shared mobile data connection just fine over hotspot, wifi sharing seems to be flaky im not sure. will look more into it when i have time

**Comment by dtriguero** [comment]
@ananjaser1211 I was able to get it working using mobile data and wifi sharing. Had to flash a different csc. Was using btu from when flashing rom because install would freeze if selected auto CSC or use previous. I used csc3.0 zip to change it to xaa which wasn't offered in the rom installation. Everything hotspot wise seems to be working now but for some reason lost options for 7x6 grid size in home and app drawer. That I'm not worried about. If want you can close this since it is now working. Thank you for your time and advice and not to mention the sweet rom 👍✌
