### ISSUE TITLE
[Enhancement] Show correct battery capacity in settings

### ISSUE THREAD

**Issue by aladie** [ananjaser1211/FloydQ_Reports#82]
**Describe the enhancement**
When you go into the settings app ->about the battery it shows a capacity of 3600 mAh, but it should be 3000 mAh for the regular S7. 

**Screenshots**
![WhatsApp Image 2020-05-10 at 11 15 23](https://user-images.githubusercontent.com/47330742/81495296-9847dd00-92af-11ea-9255-17f0b3b346b3.jpeg)

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
Its just a text, there are far more important stuff to focus on.

the text is altered after you flash the temporary WiFi fix. before it the rom auto sets that text.
