### ISSUE TITLE
[BUG] Island failing to setup

### ISSUE THREAD

**Issue by floviolleau** [ananjaser1211/FloydQ_Reports#83]
**Describe the bug**
Hi,

I'm trying to install Island but it failed. I went throught their website (https://island.oasisfeng.com) and XDA threads and I didn't found any working solutions.

I have another S7 Edge rooted under lineage OS 17.1 (Android 10) and it works fine without problems.

**To Reproduce**
1. Install Island https://play.google.com/store/apps/details?id=com.oasisfeng.island&hl=en
2. Start the app and follow instructions
3. Fail to create work profile.
4. OK
4. Setup Island with root
=> Something went wrong in Island setup (stage 1)

or install manually
1. adb -d shell
2. setprop fw.max_users 10
3. reboot
4. adb -d shell
5. pm create-user --profileOf 0 --managed Island
=> Error: couldn't create User.

**Expected behavior**
Make Island working :)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model: G935F (bought in France)

**Comment by ananjaser1211** [comment]
Ill take a look once i get the chance. in order to save time ill ask some friends who are on official One ui 2.0 devices (s9 even) just to be sure its not some limitation from the OS itself

**Comment by ananjaser1211** [comment]
i asked my friend on S9 Device running Q To try island, it failed to create profile.
it might be that the app just does not support oneui 2.0 yet.

**Comment by floviolleau** [comment]
Ok. Thanks for the feedback. Do you know any other app to be able to have for the same app 2 different contexts?

**Comment by ananjaser1211** [comment]
> Ok. Thanks for the feedback. Do you know any other app to be able to have for the same app 2 different contexts?

Doesn't samsung dual messenger do that ? you can use it for many social media apps, now that you mention it i dont remember if i patched it to support all apps

**Comment by floviolleau** [comment]
Yes you are right!! I missed that feature. I thought it was only for social apps but in fact, with your rom it works very fine for other apps. I tested with Mi home, Décathlon and pyload (the last one, I don't know why but it forces crash after couple of seconds).

Thanks!

**Comment by ananjaser1211** [comment]
I have mistaken secure folder with workprofile. while they both function the same, they are different implementations

V5 will have the real workprofile properly working, including island and any apps that require MDM

![photo_2020-10-28_16-51-55](https://user-images.githubusercontent.com/25624482/97438199-e7f19200-193d-11eb-99ba-772e19f1e814.jpg)
![photo_2020-10-28_16-51-48](https://user-images.githubusercontent.com/25624482/97438200-e922bf00-193d-11eb-9b0e-b2e30468f6e3.jpg)
![photo_2020-10-28_16-51-52](https://user-images.githubusercontent.com/25624482/97438202-e9bb5580-193d-11eb-9306-0ffe133cdf14.jpg)
![photo_2020-10-28_16-52-31](https://user-images.githubusercontent.com/25624482/97438250-fb046200-193d-11eb-9f93-5810aea49110.jpg)

**Comment by Aholicknight** [comment]
I am having this same issue on my Samsung a70 with root does anyone know how to fix

**Comment by ananjaser1211** [comment]
Re-open due to bug coming back in V7.0

**Comment by loopaz** [comment]
> I have mistaken secure folder with workprofile. while they both function the same, they are different implementations
> 
> V5 will have the real workprofile properly working, including island and any apps that require MDM
> 
> ![photo_2020-10-28_16-51-55](https://user-images.githubusercontent.com/25624482/97438199-e7f19200-193d-11eb-99ba-772e19f1e814.jpg) ![photo_2020-10-28_16-51-48](https://user-images.githubusercontent.com/25624482/97438200-e922bf00-193d-11eb-9b0e-b2e30468f6e3.jpg) ![photo_2020-10-28_16-51-52](https://user-images.githubusercontent.com/25624482/97438202-e9bb5580-193d-11eb-9306-0ffe133cdf14.jpg) ![photo_2020-10-28_16-52-31](https://user-images.githubusercontent.com/25624482/97438250-fb046200-193d-11eb-9f93-5810aea49110.jpg)

Hello.
I had a clean installation, but the island program cannot create a profile, but the profile part of the system works without any problems.
The problem of the system profile, you do not have access to other programs while running, if the island program runs the restricted program in the heart of the personal profile.
This system is very useful for us (the government spies on people with bank and government programs)

**Comment by loopaz** [comment]
I will do again from the first

**Comment by loopaz** [comment]
I will do again from the first
😊😊

**Comment by ananjaser1211** [comment]
I am creating a patch, will upload a test zip momentarily @loopaz

**Comment by ananjaser1211** [comment]
> I will do again from the first 😊😊
[FloydQ_V7_Hotfix - WorkProfile.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/9046662/FloydQ_V7_Hotfix.-.WorkProfile.zip)

Flash this patch from TWRP, WorkProfile / island app will work again.

![image](https://user-images.githubusercontent.com/25624482/177338163-52dc283c-9318-4670-aca7-29792a395c16.png)

**Comment by loopaz** [comment]
> > I will do again from the first 😊😊
> > [FloydQ_V7_Hotfix - WorkProfile.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/9046662/FloydQ_V7_Hotfix.-.WorkProfile.zip)
> 
> Flash this patch from TWRP, WorkProfile / island app will work again.
> 
> ![image](https://user-images.githubusercontent.com/25624482/177338163-52dc283c-9318-4670-aca7-29792a395c16.png)

Hello and thanks
It was made very well and Ali is working.
It just doesn't have a fingerprint yet!!
Many thanks.

**Comment by durhari** [comment]
> > > I will do again from the first 😊😊
> > > [FloydQ_V7_Hotfix - WorkProfile.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/9046662/FloydQ_V7_Hotfix.-.WorkProfile.zip)
> > 
> > 
> > Flash this patch from TWRP, WorkProfile / island app will work again.
> > ![image](https://user-images.githubusercontent.com/25624482/177338163-52dc283c-9318-4670-aca7-29792a395c16.png)
> 
> Hello and thanks It was made very well and Ali is working. It just doesn't have a fingerprint yet!! Many thanks.

@ananjaser1211 
Can i use this workprofile.zip for other roms like oneUI5.1 beyond ported for s10

**Comment by ananjaser1211** [comment]
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172
