### ISSUE TITLE
[BUG]The other party doesn`t hear me, irregular, after several calls. 

### ISSUE THREAD

**Issue by Vivigens** [ananjaser1211/FloydQ_Reports#84]
**Describe the bug**
I made two Full-Wipe-Installs on a S7edge. Coming from perfect running Black Diamond N8port. 
I have the recurring Problem, that my Interlocutor don`t hear my voice, while I hear his voice. This happens not principle, but after several calls. And both, Apple and Samsung Users. After a restart the call works fine. When I call and when I am called.... both!

**Expected behavior**
I expected to be heard. After the error occured for the first time, I imported the BD N8-backup but the problem persisted.

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7edge]
 - Model: [G935F]

No Logs available

**Comment by shariq342** [comment]
Choose your csc manually.

**Comment by Vivigens** [comment]
@shariq342 Thx for the solution! 
I installed the Rom again with manually CSC (DBT for Germany) and it seems, everything works so far!
Good job!
:-)

***closed***

**Comment by Vivigens** [comment]
Manually choosing the right **C**onsumer **S**oftware **C**ustomisationCode fixes the Issue!

**Comment by Vivigens** [comment]
The issue is back after 6 days without Problems. Maybe the CSC for Germany (DBT) must be renewed...?!

**Comment by ananjaser1211** [comment]
> The issue is back after 6 days without Problems. Maybe the CSC for Germany (DBT) must be renewed...?!

All the CSC packages will be updated in V2 (including support for 170 more countries) . while i cant guarantee it will solve your issue, will have to wait and see. 

so far the testers are unable to reproduce this bug.

**Comment by Vivigens** [comment]
Maybe there is a connection between my issue (Model/Name) and the restrictions of my telecom operator. Thx so far. Thread closed.
