### ISSUE TITLE
[BUG] SmartCases do not work

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#86]
* The bug is when  you open a case > the screen turns off, when you close a case > screen turns on

* This also caused users who have SVIEW (the case with the window) to break their touch

- The error was samsung changing HALL_IC status in Q Rom, by flipping its state. we fix this by reverting HALL_IC in the [kernel ](https://github.com/ananjaser1211/Cronos_8890/commit/48e020774204c4b1cd93d20fa148544c272b42b3)(which is the same method they use on official Q devices)

**Comment by DaveSouthUK** [comment]
The bug is still outstanding to some extent as there is no LED activity on LED covers
