### ISSUE TITLE
[BUG]Related to Messenger Camera

### ISSUE THREAD

**Issue by albertodurmiendo** [ananjaser1211/FloydQ_Reports#87]
**Describe the bug**
This post is related to post #74 , this post help me realize that there's something on my system so I clean flash again this ROM and bring back the settings I have including "Smart Stay" which I think causing problem with this bug. Now I encounter again this kind of bug but now in much cleaner logcat look (FPAuthentication spam are not visible) so I just want to take a look in this log and maybe you figure out if it is a BUG or its my devices problem 

NOTE: Fixed when restarting device.

 - Device: Galaxy S7
 - Model: G930FD

**Additional context**
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4635274/log_e.log)

**Comment by ananjaser1211** [comment]
@albertodurmiendo Thanks for the clean log, smart view does seem to cause the camera hal to die earlier that it would usually do.

in V2 i did a new approach to handling camera which seemed to reduce how often the camera server would be stuck for and eliminate it to an extent, ill have to test it in more depth with smart view on to see if the issue persists.
