### ISSUE TITLE
[BUG] Mobile data keeps disconnecting!

### ISSUE THREAD

**Issue by tanjilrahman** [ananjaser1211/FloydQ_Reports#89]
While using the usb tethering option, mobile data don't work. I have to restart mobile data every so often to keep it running.

**Comment by ananjaser1211** [comment]
Provide logs please, i dont have a SIM with data to test right now.

**Comment by tanjilrahman** [comment]
How to get the logs?

**Comment by ananjaser1211** [comment]
Come back next time when you put effort into reading the 30 second guide written here.
