### ISSUE TITLE
[BUG] Entering a password right after installing

### ISSUE THREAD

**Issue by ATI9590** [ananjaser1211/FloydQ_Reports#90]
When the phone boots up, it says I need to enter my password because the storage is encrypted; but I didn't encrypt anything.

Galaxy S7 Edge
SM-935F

**Comment by ananjaser1211** [comment]
@ATI9590 You probably did not format Data (Not wipe, FORMAT) after rooting your phone

so go to twrp > wipe > format data > press yes (all your internal will be wiped)

**Comment by ananjaser1211** [comment]
Closing as its not really a ROM issue. and you have not updated us if it was format data related or not.
