### ISSUE TITLE
[BUG] Picture-in-Picture Mode WhatsApp

### ISSUE THREAD

**Issue by igorcv7** [ananjaser1211/FloydQ_Reports#91]
**Describe the bug**
In a whatsapp video call, there are times when the camera minimizes itself and there is no minimization afterwards, as if the picture-in-picture mode was automatically disabled, after some time it comes back alone, I would like you to correct this bug as it harms very.

**To Reproduce**
1. Go to 'WhatsApp'
2. Click on 'Video call symbol of some contact and start a video call'
3. After sometimes the camera minimizes itself and there is no minimization afterwards, as if the picture-in-picture mode was automatically disabled.

**Expected behavior**
I hope that this bug can be fixed so that I can use the ROM fault-free.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7 Edge]
 - Model: [e.g. G935F]

**Comment by ananjaser1211** [comment]
BUG couldn't be recreated by testers. this could have been just a fluke with the whatsapp App. as there isnt much in the ROM that would affect this behaviour
