### ISSUE TITLE
[BUG] AR Emoji FC

### ISSUE THREAD

**Issue by Camille31400** [ananjaser1211/FloydQ_Reports#92]
**Describe the bug**
When I want to use AREmoji for create my AR Emoji he force close just after click on AR Emoji button when attemtping to launch app we can see the app (C.f Screenshot) but we can't click and the app force close

**To Reproduce**
1. Go to 'Camera'
2. Click on 'More'
3. Click on 'AR Emoji'

**Expected behavior**
I want to be able to create my AR Emoji

**Screenshots**
![image](https://user-images.githubusercontent.com/65614963/82350913-35b3b700-99fc-11ea-80e6-35f99335f876.png)

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7 Edge]
 - Model: [G935S]

**Comment by ananjaser1211** [comment]
See #20
