### ISSUE TITLE
Bixby freezes when pulling up

### ISSUE THREAD

**Issue by jonnycena5** [ananjaser1211/FloydQ_Reports#94]
When you try to open the Bixby menu Bixby voice freezes

**To Reproduce**
1. Say *Hi Bixby* or hold the Home-button
2. Swipe up
3. You see Bixby freezes
4. 

**Screenshots**
![Screenshot_20200520-231619_One UI Home](https://user-images.githubusercontent.com/65534237/82498279-00889100-9af0-11ea-9b0e-96803fa34ab1.jpg)
![Screenshot_20200520-231633_Bixby Voice](https://user-images.githubusercontent.com/65534237/82498297-07170880-9af0-11ea-9ee8-82bbcecee25f.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge 
 - Model: G965F

Please Fix this! I like and need Bixby!

**Comment by mathy007** [comment]
@jonnycena5 It's a known issue Bixby will be fixed in the next release

**Comment by jonnycena5** [comment]
Ok!
Thank you!
How long till the next release?

**Comment by mathy007** [comment]
@jonnycena5 No ETA

**Comment by ananjaser1211** [comment]
Duplicate #37
