### ISSUE TITLE
Displayed time of day does not change while making a call

### ISSUE THREAD

**Issue by DerElam** [ananjaser1211/FloydQ_Reports#96]
The phone displays the current time of day on the very left of the status bar. The displayed time of day does not change during a call.

1. Look at the time of day in the status bar
2. Receive a call and talk for at least one minute
3. Look at the time of day in the status bar
4. End call
5. The displayed time of day in the status bar did not change between steps 1 and 3

Expected behavior: The time of day displayed in the status bar should show the actual time of day, even during a call.

Device: Galaxy S7
Model: G930F

**Comment by ananjaser1211** [comment]
This is more of a oneui 2 issue than a ROM specific issue. i wont debug it
